"""Writes src/stories/art.ts from the Python art sources. Run: python3 tools/art/export_ts.py"""
import json, os, re
import cast, bgkit

OUT = os.path.join(os.path.dirname(__file__), "..", "..", "src", "stories", "art.ts")


def tidy(s):
    s = re.sub(r"\s+", " ", s)
    s = re.sub(r"(\d+\.\d{2})\d+", r"\1", s)  # trim long decimals
    return s.replace("> <", "><").strip()


chars = {}
for cid, ch in cast.all_characters().items():
    d = ch.export()
    chars[cid] = {
        "armL": tidy(d["armL"]), "armR": tidy(d["armR"]), "body": tidy(d["body"]), "head": tidy(d["head"]), "top": tidy(d["top"]),
        "eyes": {k: tidy(v) for k, v in d["eyes"].items()}, "mouth": {k: tidy(v) for k, v in d["mouth"].items()},
        "pivots": {k: [round(v[0], 1), round(v[1], 1)] for k, v in d["pivots"].items()},
    }
bgs = {k: tidy(f()) for k, f in bgkit.BACKGROUNDS.items()}
props = {k: tidy(f()) for k, f in bgkit.PROPS.items()}

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("// Generated by tools/art/export_ts.py. Do not edit by hand.\n")
    f.write("/* eslint-disable */\n")
    f.write(f"export const ACTOR_VIEWBOX = {json.dumps(list(cast.VIEWBOX))} as const;\n")
    f.write(f"export const VISEMES = {json.dumps(cast.VISEMES)} as const;\n")
    f.write("export type Viseme = (typeof VISEMES)[number];\n")
    f.write("export type EyeState = 'open' | 'half' | 'closed' | 'happy';\n")
    f.write("export type CharArt = { armL: string; armR: string; body: string; head: string; top: string; "
            "eyes: Record<EyeState, string>; mouth: Record<Viseme, string>; pivots: { armL: [number, number]; armR: [number, number]; neck: [number, number] } };\n")
    f.write(f"export const CHARS: Record<'boy' | 'girl' | 'ammamma' | 'tatayya' | 'amma' | 'nanna', CharArt> = {json.dumps(chars, ensure_ascii=False)} as any;\n")
    f.write(f"export const BG_DEFS = {json.dumps(tidy(bgkit.DEFS))};\n")
    f.write(f"export const SCREEN = {json.dumps(list(bgkit.SCREEN))} as const;\n")
    f.write(f"export const BACKGROUNDS: Record<string, string> = {json.dumps(bgs, ensure_ascii=False)};\n")
    f.write(f"export const PROPS: Record<string, string> = {json.dumps(props, ensure_ascii=False)};\n")
print(os.path.getsize(OUT) // 1024, "KB;", "chars", sum(len(json.dumps(v)) for v in chars.values()) // 1024, "KB; bgs",
      sum(len(v) for v in bgs.values()) // 1024, "KB; props", sum(len(v) for v in props.values()) // 1024, "KB")
