import type { UnitSpec } from './types';
export const PACK_D: UnitSpec[] = [
  { id: 'd-morning', name: 'Good morning at home', icon: '🌅', kind: 'sentences', rows: [
    ['అమ్మా, నేను లేచాను', 'ammaa, nenu lechaanu', 'Mom, I woke up', '🌅'],
    ['ఇంకొంచెం పడుకుంటాను', 'inkonchem padukuntaanu', 'I will sleep a little more', '😴'],
    ['త్వరగా లే', 'tvaragaa le', 'Get up quickly', '⏰'],
    ['తెల్లవారింది', 'tellavaarindi', 'It is morning', '🌄'],
    ['సూర్యుడు వచ్చాడు', 'sooryudu vachchaadu', 'The sun has come up', '☀️'],
    ['ముఖం కడుక్కో', 'mukham kadukko', 'Wash your face', '🚿'],
    ['పళ్ళు తోముకున్నావా?', 'pallu tomukunnaavaa?', 'Did you brush your teeth?', '🦷'],
    ['స్నానం చేశావా?', 'snaanam chesaavaa?', 'Did you take a bath?', '🛁'],
    ['పాలు తాగు', 'paalu taagu', 'Drink your milk', '🥛'],
  ] },
  { id: 'd-getready', name: 'Getting ready for school', icon: '🎒', kind: 'sentences', rows: [
    ['యూనిఫాం వేసుకో', 'yooniphaam vesuko', 'Put on your uniform', '👕'],
    ['బూట్లు ఎక్కడ ఉన్నాయి?', 'bootlu ekkada unnaayi?', 'Where are the shoes?', '👟'],
    ['నేను బూట్లు వేసుకుంటాను', 'nenu bootlu vesukuntaanu', 'I will put on my shoes', '👞'],
    ['జుట్టు దువ్వుకో', 'juttu duvvuko', 'Comb your hair', '💇'],
    ['నా బ్యాగ్ ఎక్కడ ఉంది?', 'naa byaag ekkada undi?', 'Where is my bag?', '🎒'],
    ['పుస్తకాలు సంచిలో పెట్టుకున్నావా?', 'pustakaalu sanchilo pettukunnaavaa?', 'Did you put the books in your bag?', '📚'],
    ['నీళ్ళ సీసా తీసుకున్నావా?', 'neella seesaa teesukunnaavaa?', 'Did you take your water bottle?', '💧'],
    ['లంచ్ బాక్స్ తీసుకో', 'lanch baaks teesuko', 'Take your lunch box', '🍱'],
    ['బస్సు వచ్చింది', 'bassu vachchindi', 'The bus has come', '🚌'],
    ['ఆలస్యం అవుతోంది', 'aalasyam avutondi', 'We are getting late', '⌛'],
    ['అమ్మా, వెళ్ళొస్తాను', 'ammaa, vellostaanu', 'Bye Mom, I am leaving', '👋'],
  ] },
  { id: 'd-school', name: 'At school', icon: '🏫', kind: 'sentences', rows: [
    ['నమస్తే టీచర్', 'namaste teechar', 'Hello teacher', '🏫'],
    ['టీచర్, నాకు అర్థం కాలేదు', 'teechar, naaku artham kaaledu', 'Teacher, I did not understand', '🙋'],
    ['మళ్ళీ చెప్పండి', 'malli cheppandi', 'Please say it again', '🗣️'],
    ['నేను హోంవర్క్ చేశాను', 'nenu homvark chesaanu', 'I did my homework', '📝'],
    ['ఇది నా స్నేహితుడు', 'idi naa snehitudu', 'This is my friend', '👦'],
    ['నా డబ్బాలో అన్నం ఉంది', 'naa dabbaalo annam undi', 'There is rice in my box', '🍱'],
    ['నీ డబ్బాలో ఏముంది?', 'nee dabbaalo aemundi?', 'What is in your box?', '🥡'],
    ['నాకు కొంచెం ఇస్తావా?', 'naaku konchem istaavaa?', 'Will you give me some?', '🤲'],
    ['బెల్ మోగింది', 'bel mogindi', 'The bell rang', '🔔'],
    ['ఇప్పుడు ఆటల సమయం', 'ippudu aatala samayam', 'It is games time now', '⚽'],
  ] },
  { id: 'd-comehome', name: 'Coming home', icon: '🏠', kind: 'sentences', rows: [
    ['అమ్మా, నేను వచ్చేశాను', 'ammaa, nenu vachchesaanu', 'Mom, I have come home', '🏠'],
    ['తలుపు తీయండి', 'talupu teeyandi', 'Please open the door', '🚪'],
    ['బడి ఎలా జరిగింది?', 'badi elaa jarigindi?', 'How was school?', '🏫'],
    ['ఇవాళ బడి చాలా బాగుంది', 'ivaala badi chaalaa baagundi', 'School was very good today', '😀'],
    ['కాళ్ళు చేతులు కడుక్కో', 'kaallu chetulu kadukko', 'Wash your hands and feet', '🧼'],
    ['బ్యాగ్ అక్కడ పెట్టు', 'byaag akkada pettu', 'Put the bag there', '🎒'],
    ['నాకు చాలా ఆకలిగా ఉంది', 'naaku chaalaa aakaligaa undi', 'I am very hungry', '🤤'],
    ['తినడానికి ఏమైనా ఉందా?', 'tinadaaniki aemainaa undaa?', 'Is there anything to eat?', '🍪'],
    ['ఇవాళ ఏం నేర్చుకున్నావు?', 'ivaala aem nerchukunnaavu?', 'What did you learn today?', '📚'],
  ] },
  { id: 'd-dining', name: 'At the dining table', icon: '🍛', kind: 'sentences', rows: [
    ['అమ్మా, అన్నం పెట్టు', 'ammaa, annam pettu', 'Mom, serve me rice', '🍚'],
    ['కొంచెం కూర వెయ్యి', 'konchem koora veyyi', 'Put a little curry', '🍛'],
    ['ఇంకొంచెం పెట్టండి', 'inkonchem pettandi', 'Please give a little more', '🍽️'],
    ['చాలా రుచిగా ఉంది', 'chaalaa ruchigaa undi', 'It is very tasty', '😋'],
    ['నాకు చాలు', 'naaku chaalu', 'I have had enough', '✋'],
    ['నాకు పప్పు అన్నం ఇష్టం', 'naaku pappu annam ishtam', 'I like dal rice', '🍲'],
    ['పెరుగు ఉందా?', 'perugu undaa?', 'Is there curd?', '🥣'],
    ['కారం ఎక్కువగా ఉంది', 'kaaram ekkuvagaa undi', 'It is too spicy', '🌶️'],
    ['నెమ్మదిగా తిను', 'nemmadigaa tinu', 'Eat slowly', '🐢'],
  ] },
  { id: 'd-grandma2', name: 'Calling Grandma, part 2', icon: '📱', kind: 'sentences', rows: [
    ['అమ్మమ్మా, ఏం చేస్తున్నారు?', 'ammammaa, aem chestunnaaru?', 'Grandma, what are you doing?', '📞'],
    ['మీరు భోజనం చేశారా?', 'meeru bhojanam chesaaraa?', 'Did you have your meal?', '🍛'],
    ['మీ ఆరోగ్యం బాగుందా?', 'mee aarogyam baagundaa?', 'Is your health good?', '💚'],
    ['నాకు మిమ్మల్ని చూడాలని ఉంది', 'naaku mimmalni choodaalani undi', 'I want to see you', '👀'],
    ['వీడియో కాల్ చేద్దామా?', 'veediyo kaal cheddaamaa?', 'Shall we make a video call?', '📹'],
    ['ఇవాళ నాకు బహుమతి వచ్చింది', 'ivaala naaku bahumati vachchindi', 'I got a prize today', '🏆'],
    ['మీరు ఏం వండారు?', 'meeru aem vandaaru?', 'What did you cook?', '🍳'],
    ['ఇంకొంచెం గట్టిగా మాట్లాడండి', 'inkonchem gattigaa maatlaadandi', 'Please speak a little louder', '🔊'],
    ['అమ్మ మీకు నమస్తే చెప్పింది', 'amma meeku namaste cheppindi', 'Mom says hello to you', '🙏'],
    ['రేపు మళ్ళీ ఫోన్ చేస్తాను', 'repu malli phon chestaanu', 'I will call again tomorrow', '📱'],
  ] },
  { id: 'd-grandpa', name: 'Time with Grandpa', icon: '👴', kind: 'sentences', rows: [
    ['తాతయ్యా, కథ చెప్పండి', 'taatayyaa, katha cheppandi', 'Grandpa, tell me a story', '📖'],
    ['ఇంకో కథ చెప్పండి', 'inko katha cheppandi', 'Tell me one more story', '📚'],
    ['నడకకు వెళ్దామా?', 'nadakaku veldaamaa?', 'Shall we go for a walk?', '🚶'],
    ['నేను మీతో వస్తాను', 'nenu meetho vastaanu', 'I will come with you', '👣'],
    ['మీ చెయ్యి పట్టుకుంటాను', 'mee cheyyi pattukuntaanu', 'I will hold your hand', '🤝'],
    ['తాతయ్యా, నన్ను ఆశీర్వదించండి', 'taatayyaa, nannu aasheervadinchandi', 'Grandpa, bless me', '🙏'],
    ['మీ చిన్నప్పుడు ఏం ఆడేవారు?', 'mee chinnappudu aem aadevaaru?', 'What did you play when you were small?', '🧒'],
    ['నాకు మీ కథలు ఇష్టం', 'naaku mee kathalu ishtam', 'I like your stories', '❤️'],
    ['తాతయ్య నాకు మిఠాయి ఇచ్చారు', 'taatayya naaku mithaayi ichchaaru', 'Grandpa gave me a sweet', '🍬'],
  ] },
  { id: 'd-manners', name: 'Polite words', icon: '🙏', kind: 'sentences', rows: [
    ['దయచేసి ఇవ్వండి', 'dayachesi ivvandi', 'Please give it', '🙏'],
    ['చాలా ధన్యవాదాలు', 'chaalaa dhanyavaadaalu', 'Thank you very much', '😊'],
    ['క్షమించండి', 'kshaminchandi', 'Sorry, excuse me', '🙇'],
    ['నన్ను క్షమించు', 'nannu kshaminchu', 'Forgive me', '😔'],
    ['నేను లోపలికి రావచ్చా?', 'nenu lopaliki raavachchaa?', 'May I come in?', '🚪'],
    ['నేను వెళ్ళొచ్చా?', 'nenu vellochchaa?', 'May I go?', '🚶'],
    ['కొంచెం పక్కకు జరగండి', 'konchem pakkaku jaragandi', 'Please move aside a little', '↔️'],
    ['మీకు స్వాగతం', 'meeku svaagatam', 'Welcome', '👋'],
    ['పర్వాలేదు', 'parvaaledu', 'It is okay, no problem', '👍'],
    ['మీరు కూర్చోండి', 'meeru koorchondi', 'Please sit down', '🪑'],
  ] },
  { id: 'd-asking', name: 'Asking for things', icon: '🤲', kind: 'sentences', rows: [
    ['నాకు ఆ బొమ్మ కావాలి', 'naaku aa bomma kaavaali', 'I want that toy', '🧸'],
    ['నాకు పెన్సిల్ ఇస్తావా?', 'naaku pensil istaavaa?', 'Will you give me a pencil?', '✏️'],
    ['నా పుస్తకం ఇవ్వు', 'naa pustakam ivvu', 'Give me my book', '📕'],
    ['నాకు ఒక గ్లాసు పాలు కావాలి', 'naaku oka glaasu paalu kaavaali', 'I want a glass of milk', '🥛'],
    ['నాకు చాక్లెట్ కావాలి', 'naaku chaaklet kaavaali', 'I want a chocolate', '🍫'],
    ['నాకు ఫోన్ ఇస్తారా?', 'naaku phon istaaraa?', 'Will you give me the phone?', '📱'],
    ['లైట్ వెయ్యండి', 'lait veyyandi', 'Please switch on the light', '💡'],
    ['ఫ్యాన్ ఆపండి', 'phyaan aapandi', 'Please turn off the fan', '🌀'],
    ['తలుపు మూయండి', 'talupu mooyandi', 'Please close the door', '🚪'],
    ['నాకు సహాయం కావాలి', 'naaku sahaayam kaavaali', 'I need help', '🆘'],
  ] },
  { id: 'd-questions', name: 'Asking questions', icon: '❓', kind: 'sentences', rows: [
    ['అది ఏమిటి?', 'adi aemiti?', 'What is that?', '❓'],
    ['నా చెప్పులు ఎక్కడ ఉన్నాయి?', 'naa cheppulu ekkada unnaayi?', 'Where are my slippers?', '👡'],
    ['నువ్వు ఎక్కడ ఉన్నావు?', 'nuvvu ekkada unnaavu?', 'Where are you?', '📍'],
    ['ఎవరు వచ్చారు?', 'evaru vachchaaru?', 'Who has come?', '🚪'],
    ['ఇతను ఎవరు?', 'itanu evaru?', 'Who is he?', '👦'],
    ['ఆమె ఎవరు?', 'aame evaru?', 'Who is she?', '👧'],
    ['ఎందుకు ఏడుస్తున్నావు?', 'enduku aedustunnaavu?', 'Why are you crying?', '😢'],
    ['ఎప్పుడు వెళ్దాం?', 'eppudu veldaam?', 'When shall we go?', '🕒'],
    ['ఇది ఎవరిది?', 'idi evaridi?', 'Whose is this?', '🤷'],
    ['నువ్వు ఏం చేస్తున్నావు?', 'nuvvu aem chestunnaavu?', 'What are you doing?', '🤔'],
    ['నీకు ఏది కావాలి?', 'neeku aedi kaavaali?', 'Which one do you want?', '👆'],
  ] },
  { id: 'd-describe', name: 'Describing things', icon: '🎨', kind: 'sentences', rows: [
    ['ఇది పెద్దది', 'idi peddadi', 'This is big', '🐘'],
    ['పాలు వేడిగా ఉన్నాయి', 'paalu vedigaa unnaayi', 'The milk is hot', '♨️'],
    ['ఐస్ క్రీమ్ చల్లగా ఉంది', 'ais kreem challagaa undi', 'The ice cream is cold', '🍦'],
    ['ఆకాశం నీలంగా ఉంది', 'aakaasam neelangaa undi', 'The sky is blue', '🔵'],
    ['ఆకులు ఆకుపచ్చగా ఉన్నాయి', 'aakulu aakupachchagaa unnaayi', 'The leaves are green', '🍃'],
    ['పువ్వు ఎర్రగా ఉంది', 'puvvu erragaa undi', 'The flower is red', '🌹'],
    ['పిల్లి తెల్లగా ఉంది', 'pilli tellagaa undi', 'The cat is white', '🐱'],
    ['కాకి నల్లగా ఉంది', 'kaaki nallagaa undi', 'The crow is black', '🐦'],
    ['అరటిపండు పసుపు రంగులో ఉంది', 'aratipandu pasupu rangulo undi', 'The banana is yellow', '🍌'],
    ['ఈ బంతి గుండ్రంగా ఉంది', 'ee banti gundrangaa undi', 'This ball is round', '🏀'],
  ] },
  { id: 'd-feelings', name: 'Feelings and health', icon: '🤒', kind: 'sentences', rows: [
    ['నాకు అలసటగా ఉంది', 'naaku alasatagaa undi', 'I am tired', '😩'],
    ['నాకు తల నొప్పిగా ఉంది', 'naaku tala noppigaa undi', 'My head aches', '🤕'],
    ['నాకు కడుపు నొప్పిగా ఉంది', 'naaku kadupu noppigaa undi', 'My stomach hurts', '🤢'],
    ['నాకు జ్వరంగా ఉంది', 'naaku jvarangaa undi', 'I have a fever', '🤒'],
    ['నాకు దగ్గు వస్తోంది', 'naaku daggu vastondi', 'I have a cough', '😷'],
    ['నాకు మందు కావాలి', 'naaku mandu kaavaali', 'I need medicine', '💊'],
    ['నాకు దెబ్బ తగిలింది', 'naaku debba tagilindi', 'I got hurt', '🩹'],
    ['ఇప్పుడు నాకు నయంగా ఉంది', 'ippudu naaku nayangaa undi', 'I feel better now', '😊'],
    ['నాకు భయంగా ఉంది', 'naaku bhayangaa undi', 'I am scared', '😨'],
    ['నాకు చాలా సంతోషంగా ఉంది', 'naaku chaalaa santoshangaa undi', 'I am very happy', '😄'],
    ['డాక్టర్ దగ్గరకు వెళ్దాం', 'daaktar daggaraku veldaam', 'Let us go to the doctor', '🏥'],
  ] },
  { id: 'd-play', name: 'Playing with friends', icon: '⚽', kind: 'sentences', rows: [
    ['మనం ఆడుకుందాం', 'manam aadukundaam', 'Let us play', '⚽'],
    ['నువ్వు నాతో ఆడతావా?', 'nuvvu naatho aadataavaa?', 'Will you play with me?', '🤝'],
    ['నా వంతు వచ్చింది', 'naa vantu vachchindi', 'It is my turn', '🙋'],
    ['ఇప్పుడు నీ వంతు', 'ippudu nee vantu', 'Now it is your turn', '👉'],
    ['బంతి నాకు విసురు', 'banti naaku visuru', 'Throw the ball to me', '🏐'],
    ['నేను గెలిచాను', 'nenu gelichaanu', 'I won', '🏆'],
    ['నువ్వు ఓడిపోయావు', 'nuvvu odipoyaavu', 'You lost', '😜'],
    ['దాగుడుమూతలు ఆడదాం', 'daagudumootalu aadadaam', 'Let us play hide and seek', '🙈'],
    ['నేను దాక్కుంటాను', 'nenu daakkuntaanu', 'I will hide', '🌳'],
    ['మనమందరం కలిసి ఆడదాం', 'manamandaram kalisi aadadaam', 'Let us all play together', '👫'],
  ] },
  { id: 'd-park', name: 'At the park', icon: '🌳', kind: 'sentences', rows: [
    ['పార్కుకు వెళ్దాం', 'paarkuku veldaam', 'Let us go to the park', '🌳'],
    ['నేను ఊయల ఊగుతాను', 'nenu ooyala oogutaanu', 'I will swing on the swing', '🧒'],
    ['నన్ను ఊయల ఊపు', 'nannu ooyala oopu', 'Push me on the swing', '🙌'],
    ['చూడు, పక్షి ఎగురుతోంది', 'choodu, pakshi egurutondi', 'Look, a bird is flying', '🐦'],
    ['ఆ చెట్టు చాలా పెద్దది', 'aa chettu chaalaa peddadi', 'That tree is very big', '🌲'],
    ['పువ్వులు కోయకూడదు', 'puvvulu koyakoodadu', 'We should not pluck flowers', '🌸'],
    ['నెమ్మదిగా వెళ్ళు, పడిపోతావు', 'nemmadigaa vellu, padipotaavu', 'Go slowly, you will fall', '⚠️'],
    ['కుక్కపిల్లను చూడు', 'kukkapillanu choodu', 'Look at the puppy', '🐶'],
    ['నాకు దాహంగా ఉంది', 'naaku daahangaa undi', 'I am thirsty', '💧'],
    ['ఇంటికి వెళ్దాం, చీకటి పడుతోంది', 'intiki veldaam, cheekati padutondi', 'Let us go home, it is getting dark', '🌆'],
  ] },
  { id: 'd-market', name: 'At the market', icon: '🛒', kind: 'sentences', rows: [
    ['అమ్మా, బజారుకు వెళ్దాం', 'ammaa, bajaaruku veldaam', 'Mom, let us go to the market', '🛒'],
    ['కిలో టమాటా ఎంత?', 'kilo tamaataa enta?', 'How much is a kilo of tomatoes?', '🍅'],
    ['ఇది చాలా ఖరీదుగా ఉంది', 'idi chaalaa khareedugaa undi', 'This is too expensive', '💰'],
    ['కొంచెం తగ్గించండి', 'konchem tagginchandi', 'Please reduce the price a little', '💵'],
    ['రెండు కిలోలు ఇవ్వండి', 'rendu kilolu ivvandi', 'Please give two kilos', '⚖️'],
    ['ఈ ఆపిల్ పండ్లు తాజాగా ఉన్నాయి', 'ee aapil pandlu taajaagaa unnaayi', 'These apples are fresh', '🍎'],
    ['నాకు అరటిపండ్లు కావాలి', 'naaku aratipandlu kaavaali', 'I want bananas', '🍌'],
    ['మామిడిపండు తియ్యగా ఉంది', 'maamidipandu tiyyagaa undi', 'The mango is sweet', '🥭'],
    ['క్యారెట్ కొందాం', 'kyaaret kondaam', 'Let us buy carrots', '🥕'],
    ['నేను డబ్బులు ఇస్తాను', 'nenu dabbulu istaanu', 'I will pay the money', '💵'],
    ['ఇంకా ఏం కావాలి?', 'inkaa aem kaavaali?', 'What else do we need?', '📝'],
  ] },
  { id: 'd-travel', name: 'Going on a trip', icon: '🚌', kind: 'sentences', rows: [
    ['బస్సు ఎక్కుదాం', 'bassu ekkudaam', 'Let us get on the bus', '🚌'],
    ['రైలు వస్తోంది', 'railu vastondi', 'The train is coming', '🚆'],
    ['నేను కిటికీ దగ్గర కూర్చుంటాను', 'nenu kitikee daggara koorchuntaanu', 'I will sit by the window', '🚌'],
    ['సీట్ బెల్ట్ పెట్టుకో', 'seet belt pettuko', 'Put on your seat belt', '🚗'],
    ['ఇంకా ఎంత దూరం?', 'inkaa enta dooram?', 'How much farther is it?', '🛣️'],
    ['ఇంకా ఎంత సేపు?', 'inkaa enta sepu?', 'How much longer?', '⏳'],
    ['మనం చేరుకున్నాం', 'manam cherukunnaam', 'We have arrived', '🏁'],
    ['కారు ఆపండి', 'kaaru aapandi', 'Please stop the car', '🛑'],
    ['నాకు వాంతి వస్తోంది', 'naaku vaanti vastondi', 'I feel like vomiting', '🤮'],
    ['టికెట్లు తీసుకున్నారా?', 'tiketlu teesukunnaaraa?', 'Did you take the tickets?', '🎫'],
  ] },
  { id: 'd-village', name: 'Visiting the village', icon: '🏡', kind: 'sentences', rows: [
    ['మనం ఊరికి వెళ్తున్నాం', 'manam ooriki veltunnaam', 'We are going to the village', '🏡'],
    ['అదిగో తాతయ్య ఇల్లు', 'adigo taatayya illu', "There is Grandpa's house", '🏠'],
    ['అమ్మమ్మా, మేము వచ్చాం', 'ammammaa, memu vachchaam', 'Grandma, we have come', '🤗'],
    ['ఇక్కడ చాలా చెట్లు ఉన్నాయి', 'ikkada chaalaa chetlu unnaayi', 'There are many trees here', '🌴'],
    ['నేను ఆవు పాలు తాగుతాను', 'nenu aavu paalu taagutaanu', "I will drink cow's milk", '🐄'],
    ['బావిలో నీళ్ళు ఉన్నాయి', 'baavilo neellu unnaayi', 'There is water in the well', '💧'],
    ['నేను ఎడ్లబండి ఎక్కుతాను', 'nenu edlabandi ekkutaanu', 'I will ride the bullock cart', '🐂'],
    ['అమ్మమ్మ వంట రుచిగా ఉంది', 'ammamma vanta ruchigaa undi', "Grandma's cooking is tasty", '🍛'],
    ['ఇక్కడ గాలి చాలా బాగుంది', 'ikkada gaali chaalaa baagundi', 'The air is very nice here', '🍃'],
    ['రాత్రి డాబా మీద పడుకుందాం', 'raatri daabaa meeda padukundaam', 'Let us sleep on the terrace at night', '🌙'],
    ['మళ్ళీ ఎప్పుడు వస్తాం?', 'malli eppudu vastaam?', 'When will we come again?', '📅'],
  ] },
  { id: 'd-festival', name: 'Festival day', icon: '🪔', kind: 'sentences', rows: [
    ['ఇవాళ పండుగ', 'ivaala panduga', 'Today is a festival', '🎉'],
    ['నేను కొత్త బట్టలు వేసుకున్నాను', 'nenu kotta battalu vesukunnaanu', 'I wore new clothes', '👗'],
    ['ఈ పరికిణీ చాలా బాగుంది', 'ee parikinee chaalaa baagundi', 'This long skirt is very pretty', '💃'],
    ['స్వీట్లు తిందాం', 'sveetlu tindaam', 'Let us eat sweets', '🍬'],
    ['దీపాలు వెలిగించండి', 'deepaalu veliginchandi', 'Light the lamps', '🪔'],
    ['ఇంటి ముందు ముగ్గు వేద్దాం', 'inti mundu muggu veddaam', 'Let us draw rangoli in front of the house', '🌼'],
    ['నేను గాలిపటం ఎగరేస్తాను', 'nenu gaalipatam egarestaanu', 'I will fly a kite', '🪁'],
    ['ఆకాశంలో చాలా గాలిపటాలు ఉన్నాయి', 'aakaasamlo chaalaa gaalipataalu unnaayi', 'There are many kites in the sky', '🌤️'],
    ['అందరికీ పండుగ శుభాకాంక్షలు', 'andarikee panduga shubhaakaankshalu', 'Happy festival to everyone', '🎊'],
    ['పూజ చేద్దాం', 'pooja cheddaam', 'Let us do the pooja', '🙏'],
    ['పాయసం చాలా తియ్యగా ఉంది', 'paayasam chaalaa tiyyagaa undi', 'The payasam is very sweet', '🍮'],
  ] },
  { id: 'd-weather', name: 'Weather talk', icon: '🌦️', kind: 'sentences', rows: [
    ['వర్షం పడుతోంది', 'varsham padutondi', 'It is raining', '🌧️'],
    ['గొడుగు తీసుకో', 'godugu teesuko', 'Take the umbrella', '☔'],
    ['చాలా ఎండగా ఉంది', 'chaalaa endagaa undi', 'It is very sunny', '☀️'],
    ['చాలా వేడిగా ఉంది', 'chaalaa vedigaa undi', 'It is very hot', '🥵'],
    ['చల్లటి గాలి వీస్తోంది', 'challati gaali veestondi', 'A cold wind is blowing', '🌬️'],
    ['నాకు చలిగా ఉంది', 'naaku chaligaa undi', 'I feel cold', '🥶'],
    ['స్వెటర్ వేసుకో', 'svetar vesuko', 'Wear a sweater', '🧥'],
    ['ఆకాశంలో మేఘాలు ఉన్నాయి', 'aakaasamlo meghaalu unnaayi', 'There are clouds in the sky', '☁️'],
    ['వాన ఆగింది', 'vaana aagindi', 'The rain has stopped', '🌤️'],
    ['ఆకాశంలో ఇంద్రధనుస్సు ఉంది', 'aakaasamlo indradhanussu undi', 'There is a rainbow in the sky', '🌈'],
    ['నేను వానలో తడిచాను', 'nenu vaanalo tadichaanu', 'I got wet in the rain', '💦'],
  ] },
  { id: 'd-temple', name: 'At the temple', icon: '🛕', kind: 'sentences', rows: [
    ['గుడికి వెళ్దాం', 'gudiki veldaam', 'Let us go to the temple', '🛕'],
    ['చెప్పులు బయట విడిచిపెట్టు', 'cheppulu bayata vidichipettu', 'Leave your slippers outside', '👡'],
    ['దేవుడికి నమస్కారం చెయ్యి', 'devudiki namaskaaram cheyyi', 'Bow to God', '🙏'],
    ['కొబ్బరికాయ కొడదాం', 'kobbarikaaya kodadaam', 'Let us break a coconut', '🥥'],
    ['పూలు తీసుకో', 'poolu teesuko', 'Take the flowers', '💐'],
    ['అగరబత్తి వెలిగించు', 'agarabatti veliginchu', 'Light the incense stick', '🕯️'],
    ['గంట కొట్టు', 'ganta kottu', 'Ring the bell', '🔔'],
    ['హారతి తీసుకో', 'haarati teesuko', 'Take the aarti', '🪔'],
    ['ప్రసాదం ఇవ్వండి', 'prasaadam ivvandi', 'Please give prasadam', '🍚'],
    ['పూజారి గారు మంత్రాలు చదువుతున్నారు', 'poojaari gaaru mantraalu chaduvutunnaaru', 'The priest is chanting mantras', '📿'],
    ['కళ్ళు మూసుకుని దణ్ణం పెట్టు', 'kallu moosukuni dannam pettu', 'Close your eyes and pray', '🙏'],
  ] },
  { id: 'd-bedtime', name: 'Bedtime', icon: '🌙', kind: 'sentences', rows: [
    ['పైజామా వేసుకో', 'paijaamaa vesuko', 'Put on your pyjamas', '👖'],
    ['ఇప్పుడు పడుకునే సమయం', 'ippudu padukune samayam', 'It is time to sleep now', '🛏️'],
    ['అమ్మా, కథ చెప్పు', 'ammaa, katha cheppu', 'Mom, tell me a story', '📖'],
    ['నాకు ఆవులింత వస్తోంది', 'naaku aavulinta vastondi', 'I am yawning', '🥱'],
    ['శుభ రాత్రి', 'shubha raatri', 'Good night', '🌙'],
    ['హాయిగా నిద్రపో', 'haayigaa nidrapo', 'Sleep well', '😴'],
    ['నా పక్కన పడుకో', 'naa pakkana paduko', 'Sleep next to me', '🛌'],
    ['దుప్పటి కప్పుకో', 'duppati kappuko', 'Cover yourself with the blanket', '🛏️'],
    ['రేపు పొద్దున్నే లేద్దాం', 'repu poddunne leddaam', 'Let us get up early tomorrow', '⏰'],
    ['మంచి కలలు రావాలి', 'manchi kalalu raavaali', 'Sweet dreams', '💭'],
  ] },
  { id: 'd-helping', name: 'Helping at home', icon: '🧹', kind: 'sentences', rows: [
    ['నేను ఊడుస్తాను', 'nenu oodustaanu', 'I will sweep', '🧹'],
    ['మొక్కలకు నీళ్ళు పోస్తాను', 'mokkalaku neellu postaanu', 'I will water the plants', '🌱'],
    ['నేను కంచం పెడతాను', 'nenu kancham pedataanu', 'I will set the plate', '🍽️'],
    ['బట్టలు మడతపెడతాను', 'battalu madatapedataanu', 'I will fold the clothes', '👕'],
    ['నేను సాయం చేస్తాను', 'nenu saayam chestaanu', 'I will help', '🤝'],
    ['బొమ్మలు సర్దుకుంటాను', 'bommalu sardukuntaanu', 'I will tidy my toys', '🧸'],
    ['చెత్త డబ్బాలో వెయ్యి', 'chetta dabbaalo veyyi', 'Throw the trash in the bin', '🗑️'],
    ['అమ్మకు సహాయం చెయ్యి', 'ammaku sahaayam cheyyi', 'Help Mom', '👩'],
    ['కూరగాయలు కడుగుతాను', 'kooragaayalu kadugutaanu', 'I will wash the vegetables', '🥬'],
    ['బల్ల తుడుస్తాను', 'balla tudustaanu', 'I will wipe the table', '🧽'],
    ['మంచి పని చేశావు', 'manchi pani chesaavu', 'You did good work', '👏'],
  ] },
  { id: 'd-birthday', name: 'Birthday wishes', icon: '🎂', kind: 'sentences', rows: [
    ['పుట్టినరోజు శుభాకాంక్షలు', 'puttinaroju shubhaakaankshalu', 'Happy birthday', '🎂'],
    ['ఇవాళ నా పుట్టినరోజు', 'ivaala naa puttinaroju', 'Today is my birthday', '🎈'],
    ['ఇవాళ నాకు ఏడేళ్ళు నిండాయి', 'ivaala naaku aedellu nindaayi', 'I turned seven today', '7️⃣'],
    ['కేక్ కోద్దాం', 'kek koddaam', 'Let us cut the cake', '🍰'],
    ['కొవ్వొత్తులు ఊదు', 'kovvottulu oodu', 'Blow out the candles', '🕯️'],
    ['నీకు బహుమతి తెచ్చాను', 'neeku bahumati techchaanu', 'I brought you a gift', '🎁'],
    ['ఇది నీ కోసమే', 'idi nee kosame', 'This is just for you', '💝'],
    ['నువ్వు నూరేళ్ళు బతకాలి', 'nuvvu noorellu batakaali', 'May you live a hundred years', '🎉'],
    ['అందరం పాట పాడదాం', 'andaram paata paadadaam', 'Let us all sing a song', '🎶'],
    ['నా స్నేహితులు వచ్చారు', 'naa snehitulu vachchaaru', 'My friends have come', '🥳'],
    ['కేక్ చాలా రుచిగా ఉంది', 'kek chaalaa ruchigaa undi', 'The cake is very tasty', '😋'],
  ] },
  { id: 'd-me', name: 'All about me', icon: '🙋', kind: 'sentences', rows: [
    ['నా పేరు రవి', 'naa peru ravi', 'My name is Ravi', '🙋'],
    ['నా వయసు ఏడేళ్ళు', 'naa vayasu aedellu', 'I am seven years old', '🎂'],
    ['నేను అమెరికాలో ఉంటాను', 'nenu amerikaalo untaanu', 'I live in America', '🌎'],
    ['నేను తెలుగు మాట్లాడతాను', 'nenu telugu maatlaadataanu', 'I speak Telugu', '🗣️'],
    ['నాకు తెలుగు నేర్చుకోవడం ఇష్టం', 'naaku telugu nerchukovadam ishtam', 'I like learning Telugu', '📚'],
    ['నాకు బొమ్మలు గీయడం ఇష్టం', 'naaku bommalu geeyadam ishtam', 'I like drawing pictures', '🎨'],
    ['నాకు క్రికెట్ ఇష్టం', 'naaku kriket ishtam', 'I like cricket', '🏏'],
    ['నాకు ఒక అన్నయ్య ఉన్నాడు', 'naaku oka annayya unnaadu', 'I have an elder brother', '👦'],
    ['నాకు ఒక చెల్లి ఉంది', 'naaku oka chelli undi', 'I have a younger sister', '👧'],
    ['నేను మూడో తరగతి చదువుతున్నాను', 'nenu moodo taragati chaduvutunnaanu', 'I am in third grade', '🏫'],
  ] },
  { id: 'd-numbers', name: 'Numbers and time', icon: '🕔', kind: 'sentences', rows: [
    ['ఇప్పుడు ఐదు గంటలు అయింది', 'ippudu aidu gantalu ayindi', 'It is five o clock now', '🕔'],
    ['నా దగ్గర రెండు ఆపిల్ పండ్లు ఉన్నాయి', 'naa daggara rendu aapil pandlu unnaayi', 'I have two apples', '🍎'],
    ['ఇవాళ సోమవారం', 'ivaala somavaaram', 'Today is Monday', '📅'],
    ['రేపు మంగళవారం', 'repu mangalavaaram', 'Tomorrow is Tuesday', '🗓️'],
    ['నిన్న ఆదివారం', 'ninna aadivaaram', 'Yesterday was Sunday', '☀️'],
    ['మూడు పిల్లులు ఉన్నాయి', 'moodu pillulu unnaayi', 'There are three cats', '🐱'],
    ['నాకు నాలుగు బిస్కెట్లు కావాలి', 'naaku naalugu bisketlu kaavaali', 'I want four biscuits', '🍪'],
    ['ఎనిమిదికి బడి మొదలవుతుంది', 'enimidiki badi modalavutundi', 'School starts at eight', '🏫'],
    ['ఇప్పుడు ఎంత టైం అయింది?', 'ippudu enta taim ayindi?', 'What time is it now?', '⏰'],
    ['పది నిమిషాలు ఆగు', 'padi nimishaalu aagu', 'Wait ten minutes', '⏱️'],
    ['ఆరు గంటలకు వస్తాను', 'aaru gantalaku vastaanu', 'I will come at six o clock', '🕕'],
  ] },
  { id: 'd-love', name: 'Love and blessings', icon: '💖', kind: 'sentences', rows: [
    ['అమ్మా, నువ్వంటే నాకు చాలా ఇష్టం', 'ammaa, nuvvante naaku chaalaa ishtam', 'Mom, I love you very much', '💖'],
    ['మీరంటే నాకు చాలా ఇష్టం', 'meerante naaku chaalaa ishtam', 'I love you very much (to elders)', '❤️'],
    ['అమ్మమ్మా, నన్ను దీవించండి', 'ammammaa, nannu deevinchandi', 'Grandma, bless me', '🙏'],
    ['జాగ్రత్తగా ఉండు', 'jaagrattagaa undu', 'Take care', '🤗'],
    ['జాగ్రత్తగా వెళ్ళి రండి', 'jaagrattagaa velli randi', 'Go safely', '🚗'],
    ['మళ్ళీ త్వరగా రండి', 'malli tvaragaa randi', 'Come back soon', '🏃'],
    ['మిమ్మల్ని చాలా మిస్ అవుతున్నాను', 'mimmalni chaalaa mis avutunnaanu', 'I miss you a lot', '🥺'],
    ['మీరు ఎప్పుడూ నా మనసులో ఉంటారు', 'meeru eppudoo naa manasulo untaaru', 'You are always in my heart', '💛'],
    ['నీకు ముద్దు పెడతాను', 'neeku muddu pedataanu', 'I will give you a kiss', '😘'],
    ['మీ ఆశీర్వాదం కావాలి', 'mee aasheervaadam kaavaali', 'I need your blessings', '🙇'],
    ['దేవుడు నిన్ను చల్లగా చూడాలి', 'devudu ninnu challagaa choodaali', 'May God keep you well', '🌟'],
    ['మళ్ళీ త్వరలో కలుద్దాం', 'malli tvaralo kaluddaam', 'Let us meet again soon', '👋'],
  ] },
];
