import type { UnitSpec } from './types';
export const PACK_B: UnitSpec[] = [
  { id: 'b-farm', name: 'On the farm', icon: '🚜', rows: [
    ['గేదె', 'gede', 'Buffalo', '🐃'],
    ['మేక', 'meka', 'Goat', '🐐'],
    ['గొర్రె', 'gorre', 'Sheep', '🐑'],
    ['ఎద్దు', 'eddu', 'Bull', '🐂'],
    ['దూడ', 'dooda', 'Calf', '🐮'],
    ['పంది', 'pandi', 'Pig', '🐖'],
    ['గాడిద', 'gaadida', 'Donkey', '🐴'],
    ['కోడిపెట్ట', 'kodipetta', 'Hen', '🐔'],
    ['కోడిపిల్ల', 'kodipilla', 'Chick', '🐥'],
    ['పొట్టేలు', 'pottelu', 'Ram', '🐏'],
    ['కుక్కపిల్ల', 'kukkapilla', 'Puppy', '🐶'],
  ] },
  { id: 'b-wild', name: 'Wild animals', icon: '🦁', rows: [
    ['సింహం', 'simham', 'Lion', '🦁'],
    ['ఎలుగుబంటి', 'elugubanti', 'Bear', '🐻'],
    ['జింక', 'jinka', 'Deer', '🦌'],
    ['తోడేలు', 'todelu', 'Wolf', '🐺'],
    ['నక్క', 'nakka', 'Fox', '🦊'],
    ['కుందేలు', 'kundelu', 'Rabbit', '🐰'],
    ['జిరాఫీ', 'jiraafee', 'Giraffe', '🦒'],
    ['జీబ్రా', 'jeebraa', 'Zebra', '🦓'],
    ['చిరుతపులి', 'chirutapuli', 'Leopard', '🐆'],
    ['ఉడుత', 'uduta', 'Squirrel', '🐿️'],
    ['గబ్బిలం', 'gabbilam', 'Bat', '🦇'],
    ['ఖడ్గమృగం', 'khadgamrugam', 'Rhino', '🦏'],
  ] },
  { id: 'b-birds', name: 'Birds', icon: '🦚', rows: [
    ['కాకి', 'kaaki', 'Crow', '🐦'],
    ['నెమలి', 'nemali', 'Peacock', '🦚'],
    ['పిచ్చుక', 'pichchuka', 'Sparrow', '🐤'],
    ['గుడ్లగూబ', 'gudlagooba', 'Owl', '🦉'],
    ['గద్ద', 'gadda', 'Eagle', '🦅'],
    ['బాతు', 'baatu', 'Duck', '🦆'],
    ['పావురం', 'paavuram', 'Pigeon', '🕊️'],
    ['హంస', 'hamsa', 'Swan', '🦢'],
    ['కోకిల', 'kokila', 'Cuckoo', '🎶'],
    ['ఈక', 'eeka', 'Feather', '🦚'],
  ] },
  { id: 'b-bugs', name: 'Bugs and crawlers', icon: '🦋', rows: [
    ['చీమ', 'cheema', 'Ant', '🐜'],
    ['తేనెటీగ', 'teneteega', 'Honey bee', '🐝'],
    ['సీతాకోకచిలుక', 'seetaakokachiluka', 'Butterfly', '🦋'],
    ['సాలీడు', 'saaleedu', 'Spider', '🕷️'],
    ['పాము', 'paamu', 'Snake', '🐍'],
    ['కప్ప', 'kappa', 'Frog', '🐸'],
    ['నత్త', 'natta', 'Snail', '🐌'],
    ['దోమ', 'doma', 'Mosquito', '🦟'],
    ['బల్లి', 'balli', 'Lizard', '🦎'],
    ['తేలు', 'telu', 'Scorpion', '🦂'],
    ['గొంగళి పురుగు', 'gongali purugu', 'Caterpillar', '🐛'],
    ['మిడత', 'midata', 'Grasshopper', '🦗'],
  ] },
  { id: 'b-water', name: 'Water animals', icon: '🐬', rows: [
    ['తిమింగలం', 'timingalam', 'Whale', '🐋'],
    ['డాల్ఫిన్', 'daalphin', 'Dolphin', '🐬'],
    ['పీత', 'peeta', 'Crab', '🦀'],
    ['తాబేలు', 'taabelu', 'Turtle', '🐢'],
    ['ఆక్టోపస్', 'aaktopas', 'Octopus', '🐙'],
    ['రొయ్య', 'royya', 'Prawn', '🦐'],
    ['షార్క్', 'shaark', 'Shark', '🦈'],
    ['మొసలి', 'mosali', 'Crocodile', '🐊'],
    ['ఆల్చిప్ప', 'aalchippa', 'Seashell', '🐚'],
    ['వల', 'vala', 'Fishing net', '🥅'],
    ['గాలం', 'gaalam', 'Fishing hook', '🎣'],
  ] },
  { id: 'b-trees', name: 'Trees and plants', icon: '🌳', rows: [
    ['వేప', 'vepa', 'Neem tree', '🌳'],
    ['మర్రిచెట్టు', 'marrichettu', 'Banyan tree', '🌲'],
    ['కొబ్బరిచెట్టు', 'kobbarichettu', 'Coconut tree', '🌴'],
    ['మామిడిచెట్టు', 'maamidichettu', 'Mango tree', '🥭'],
    ['తులసి', 'tulasi', 'Tulsi plant', '🌿'],
    ['గడ్డి', 'gaddi', 'Grass', '🌾'],
    ['ఆకు', 'aaku', 'Leaf', '🍃'],
    ['వేరు', 'veru', 'Root', '🥕'],
    ['కొమ్మ', 'komma', 'Branch', '☘️'],
    ['విత్తనం', 'vittanam', 'Seed', '🌰'],
    ['మొక్క', 'mokka', 'Small plant', '🌱'],
    ['ముల్లు', 'mullu', 'Thorn', '🌵'],
  ] },
  { id: 'b-flowers', name: 'Flowers', icon: '🌺', rows: [
    ['గులాబీ', 'gulaabee', 'Rose', '🌹'],
    ['మల్లెపువ్వు', 'mallepuvvu', 'Jasmine', '💮'],
    ['తామర', 'taamara', 'Lotus', '🌸'],
    ['బంతిపువ్వు', 'bantipuvvu', 'Marigold', '🌼'],
    ['మందారం', 'mandaaram', 'Hibiscus', '🌺'],
    ['చామంతి', 'chaamanti', 'Chrysanthemum', '🏵️'],
    ['పొద్దుతిరుగుడు', 'poddutirugudu', 'Sunflower', '🌻'],
    ['మొగ్గ', 'mogga', 'Bud', '🌱'],
    ['రేక', 'reka', 'Petal', '🌷'],
    ['పూలగుత్తి', 'poolagutti', 'Bouquet', '💐'],
    ['సువాసన', 'suvaasana', 'Sweet smell', '👃'],
    ['తేనె', 'tene', 'Honey', '🍯'],
  ] },
  { id: 'b-weather', name: 'Weather and seasons', icon: '⛅', rows: [
    ['మేఘం', 'megham', 'Cloud', '☁️'],
    ['ఉరుము', 'urumu', 'Thunder', '🌩️'],
    ['తుఫాను', 'tuphaanu', 'Storm', '⛈️'],
    ['ఎండ', 'enda', 'Sunshine', '☀️'],
    ['చలి', 'chali', 'Cold', '🥶'],
    ['శీతాకాలం', 'sheetaakaalam', 'Winter', '❄️'],
    ['వేసవికాలం', 'vesavikaalam', 'Summer', '🌞'],
    ['వర్షాకాలం', 'varshaakaalam', 'Rainy season', '☔'],
    ['వసంతకాలం', 'vasantakaalam', 'Spring', '🌸'],
    ['పొగమంచు', 'pogamanchu', 'Fog', '🌫️'],
    ['మంచు', 'manchu', 'Snow', '⛄'],
    ['వరద', 'varada', 'Flood', '🌊'],
  ] },
  { id: 'b-land', name: 'Land and water', icon: '🏔️', rows: [
    ['కొండ', 'konda', 'Hill', '⛰️'],
    ['పర్వతం', 'parvatam', 'Mountain', '🏔️'],
    ['అడవి', 'adavi', 'Forest', '🌲'],
    ['సరస్సు', 'sarassu', 'Lake', '🏞️'],
    ['ద్వీపం', 'dveepam', 'Island', '🏝️'],
    ['రోడ్డు', 'roddu', 'Road', '🛣️'],
    ['వంతెన', 'vantena', 'Bridge', '🌉'],
    ['చెరువు', 'cheruvu', 'Pond', '🦆'],
    ['ఎడారి', 'edaari', 'Desert', '🏜️'],
    ['గుహ', 'guha', 'Cave', '🕳️'],
    ['జలపాతం', 'jalapaatam', 'Waterfall', '🌊'],
    ['బావి', 'baavi', 'Well', '💧'],
  ] },
  { id: 'b-sky', name: 'Sky and space', icon: '🪐', rows: [
    ['గ్రహం', 'graham', 'Planet', '🪐'],
    ['భూమి', 'bhoomi', 'Earth', '🌍'],
    ['మెరుపు', 'merupu', 'Lightning', '⚡'],
    ['ఇంద్రధనస్సు', 'indradhanassu', 'Rainbow', '🌈'],
    ['తోకచుక్క', 'tokachukka', 'Comet', '☄️'],
    ['వెన్నెల', 'vennela', 'Moonlight', '🌙'],
    ['అంతరిక్షం', 'antariksham', 'Space', '🌌'],
    ['రాకెట్', 'raaket', 'Rocket', '🚀'],
    ['సూర్యాస్తమయం', 'sooryaastamayam', 'Sunset', '🌇'],
    ['సూర్యోదయం', 'sooryodayam', 'Sunrise', '🌅'],
    ['అమావాస్య', 'amaavaasya', 'New moon', '🌑'],
    ['పౌర్ణమి', 'paurnami', 'Full moon', '🌕'],
  ] },
  { id: 'b-vehicles', name: 'Vehicles', icon: '🚗', rows: [
    ['కారు', 'kaaru', 'Car', '🚗'],
    ['బైక్', 'baik', 'Motorbike', '🏍️'],
    ['సైకిల్', 'saikil', 'Bicycle', '🚲'],
    ['లారీ', 'laaree', 'Lorry', '🚚'],
    ['పడవ', 'padava', 'Boat', '⛵'],
    ['ఓడ', 'oda', 'Ship', '🚢'],
    ['ట్రాక్టర్', 'traaktar', 'Tractor', '🚜'],
    ['ఎడ్లబండి', 'edlabandi', 'Bullock cart', '🐂'],
    ['హెలికాప్టర్', 'helikaaptar', 'Helicopter', '🚁'],
    ['ఆటో', 'aato', 'Auto rickshaw', '🛺'],
    ['అంబులెన్స్', 'ambulens', 'Ambulance', '🚑'],
    ['స్కూటర్', 'skootar', 'Scooter', '🛵'],
  ] },
  { id: 'b-jobs', name: 'People who help us', icon: '👩‍⚕️', rows: [
    ['దర్జీ', 'darjee', 'Tailor', '🧵'],
    ['సైనికుడు', 'sainikudu', 'Soldier', '💂'],
    ['వడ్రంగి', 'vadrangi', 'Carpenter', '🔨'],
    ['కుమ్మరి', 'kummari', 'Potter', '🏺'],
    ['దుకాణదారుడు', 'dukaanadaarudu', 'Shopkeeper', '🏪'],
    ['గాయకుడు', 'gaayakudu', 'Singer', '🎤'],
  ] },
  { id: 'b-town', name: 'Places in town', icon: '🏙️', rows: [
    ['మార్కెట్', 'maarket', 'Market', '🛒'],
    ['బ్యాంకు', 'byaanku', 'Bank', '🏦'],
    ['పోస్టాఫీసు', 'postaapheesu', 'Post office', '🏤'],
    ['పార్కు', 'paarku', 'Park', '🌳'],
    ['సినిమా హాలు', 'sinimaa haalu', 'Cinema', '🎬'],
    ['గ్రంథాలయం', 'granthaalayam', 'Library', '📚'],
    ['హోటల్', 'hotal', 'Hotel', '🏨'],
    ['రైల్వే స్టేషన్', 'railve steshan', 'Railway station', '🚉'],
    ['బస్టాండ్', 'bastaand', 'Bus stand', '🚏'],
    ['చర్చి', 'charchi', 'Church', '⛪'],
    ['మసీదు', 'maseedu', 'Mosque', '🕌'],
    ['పెట్రోల్ బంక్', 'petrol bank', 'Petrol pump', '⛽'],
  ] },
  { id: 'b-school', name: 'In my school bag', icon: '🎒', rows: [
    ['పెన్ను', 'pennu', 'Pen', '🖊️'],
    ['పెన్సిల్', 'pensil', 'Pencil', '✏️'],
    ['బ్యాగు', 'byaagu', 'School bag', '🎒'],
    ['నోటుబుక్', 'nootubuk', 'Notebook', '📓'],
    ['బోర్డు', 'bordu', 'Board', '📋'],
    ['తరగతి', 'taragati', 'Class', '🏫'],
    ['పాఠం', 'paatham', 'Lesson', '📖'],
    ['పరీక్ష', 'pareeksha', 'Exam', '📝'],
    ['రబ్బరు', 'rabbaru', 'Eraser', '🧽'],
    ['స్కేలు', 'skelu', 'Ruler', '📏'],
    ['కత్తెర', 'kattera', 'Scissors', '✂️'],
    ['జిగురు', 'jiguru', 'Glue', '🧴'],
  ] },
  { id: 'b-body2', name: 'My body 2', icon: '🧍', rows: [
    ['మెడ', 'meda', 'Neck', '🧣'],
    ['భుజం', 'bhujam', 'Shoulder', '🤷'],
    ['వేలు', 'velu', 'Finger', '☝️'],
    ['గోరు', 'goru', 'Nail', '💅'],
    ['మోచేయి', 'mocheyi', 'Elbow', '💪'],
    ['మోకాలు', 'mokaalu', 'Knee', '🦵'],
    ['వీపు', 'veepu', 'Back', '🚶'],
    ['ఛాతీ', 'chhaatee', 'Chest', '👕'],
    ['చర్మం', 'charmam', 'Skin', '✋'],
    ['నాలుక', 'naaluka', 'Tongue', '👅'],
    ['పెదవులు', 'pedavulu', 'Lips', '👄'],
    ['నుదురు', 'nuduru', 'Forehead', '🤕'],
  ] },
  { id: 'b-body3', name: 'My body 3', icon: '🦴', rows: [
    ['బుగ్గ', 'bugga', 'Cheek', '😊'],
    ['కనుబొమ్మ', 'kanubomma', 'Eyebrow', '🤨'],
    ['మడమ', 'madama', 'Heel', '👣'],
    ['బొటనవేలు', 'botanavelu', 'Thumb', '👍'],
    ['అరచేయి', 'aracheyi', 'Palm', '🖐️'],
    ['కాలివేలు', 'kaalivelu', 'Toe', '🦶'],
    ['గడ్డం', 'gaddam', 'Beard', '🧔'],
    ['మీసం', 'meesam', 'Moustache', '👨'],
    ['గొంతు', 'gontu', 'Throat', '🗣️'],
    ['ఎముక', 'emuka', 'Bone', '🦴'],
    ['గుండె', 'gunde', 'Heart', '❤️'],
    ['మణికట్టు', 'manikattu', 'Wrist', '⌚'],
  ] },
  { id: 'b-clothes', name: 'Clothes 2', icon: '👖', rows: [
    ['ప్యాంటు', 'pyaantu', 'Pants', '👖'],
    ['ఫ్రాక్', 'phraak', 'Frock', '👗'],
    ['ధోతి', 'dhoti', 'Dhoti', '🥋'],
    ['కుర్తా', 'kurtaa', 'Kurta', '👘'],
    ['శాలువా', 'shaaluvaa', 'Shawl', '🧣'],
    ['సాక్సులు', 'saaksulu', 'Socks', '🧦'],
    ['బూట్లు', 'bootlu', 'Shoes', '👟'],
    ['షార్ట్స్', 'shaarts', 'Shorts', '🩳'],
    ['స్వెటర్', 'svetar', 'Sweater', '🧶'],
    ['కోటు', 'kotu', 'Coat', '🧥'],
    ['జేబు', 'jebu', 'Pocket', '👝'],
    ['గుండీ', 'gundee', 'Button', '🔘'],
  ] },
  { id: 'b-jewels', name: 'Jewels and festival dress', icon: '💍', rows: [
    ['గాజులు', 'gaajulu', 'Bangles', '⭕'],
    ['హారం', 'haaram', 'Necklace', '📿'],
    ['చెవిపోగులు', 'chevipogulu', 'Earrings', '💎'],
    ['బొట్టు', 'bottu', 'Bindi', '🔴'],
    ['పట్టీలు', 'patteelu', 'Anklets', '👣'],
    ['తలలో పూలు', 'talalo poolu', 'Flowers in hair', '💐'],
    ['ఉంగరం', 'ungaram', 'Ring', '💍'],
    ['పట్టు చీర', 'pattu cheera', 'Silk saree', '🥻'],
    ['లంగా ఓణీ', 'langaa onee', 'Half saree', '👗'],
    ['జడ', 'jada', 'Braid', '🎀'],
    ['గోరింటాకు', 'gorintaaku', 'Henna', '🌿'],
  ] },
  { id: 'b-festivals', name: 'Festivals 2', icon: '🎉', rows: [
    ['బతుకమ్మ', 'batukamma', 'Bathukamma', '🌼'],
    ['బోనాలు', 'bonaalu', 'Bonalu', '🍲'],
    ['దసరా', 'dasaraa', 'Dasara', '🏹'],
    ['హోలీ', 'holee', 'Holi', '🎨'],
    ['రాఖీ', 'raakhee', 'Rakhi', '🧵'],
    ['వినాయక చవితి', 'vinaayaka chaviti', 'Ganesh festival', '🐘'],
    ['భోగి', 'bhogi', 'Bhogi', '🔥'],
    ['కనుమ', 'kanuma', 'Kanuma', '🐄'],
    ['పంట', 'panta', 'Harvest', '🌾'],
    ['గంగిరెద్దు', 'gangireddu', 'Decorated bull', '🐂'],
    ['క్రిస్మస్', 'krismas', 'Christmas', '🎄'],
  ] },
  { id: 'b-culture', name: 'Telugu culture', icon: '🪔', rows: [
    ['నృత్యం', 'nrutyam', 'Dance', '💃'],
    ['పాట', 'paata', 'Song', '🎵'],
    ['పూజ', 'pooja', 'Pooja', '🪔'],
    ['పూలదండ', 'pooladanda', 'Garland', '🌺'],
    ['గుడి గంట', 'gudi ganta', 'Temple bell', '🔔'],
    ['హరికథ', 'harikatha', 'Harikatha', '🎙️'],
    ['జానపద కళ', 'jaanapada kala', 'Folk art', '🎨'],
    ['కూచిపూడి', 'koochipoodi', 'Kuchipudi dance', '🩰'],
    ['తోలుబొమ్మలాట', 'tolubommalaata', 'Puppet show', '🎎'],
    ['వీణ', 'veena', 'Veena', '🪕'],
    ['పద్యం', 'padyam', 'Poem', '📜'],
  ] },
  { id: 'b-shapes', name: 'Shapes and materials', icon: '🔺', rows: [
    ['వృత్తం', 'vruttam', 'Circle', '🔴'],
    ['చతురస్రం', 'chaturasram', 'Square', '🟦'],
    ['త్రిభుజం', 'tribhujam', 'Triangle', '🔺'],
    ['దీర్ఘచతురస్రం', 'deerghachaturasram', 'Rectangle', '🟩'],
    ['బంగారం', 'bangaaram', 'Gold', '🥇'],
    ['వెండి', 'vendi', 'Silver', '🥈'],
    ['ఇనుము', 'inumu', 'Iron', '⚙️'],
    ['చెక్క', 'chekka', 'Wood', '🌲'],
    ['రాయి', 'raayi', 'Stone', '🗿'],
    ['గాజు', 'gaaju', 'Glass', '🍷'],
    ['కాగితం', 'kaagitam', 'Paper', '📄'],
    ['ప్లాస్టిక్', 'plaastik', 'Plastic', '🥤'],
  ] },
  { id: 'b-toys', name: 'Toys and games', icon: '⚽', rows: [
    ['బంతి', 'banti', 'Ball', '⚽'],
    ['బొంగరం', 'bongaram', 'Spinning top', '🌀'],
    ['గోళీలు', 'goleelu', 'Marbles', '🔮'],
    ['ఊయల', 'ooyala', 'Swing', '🎠'],
    ['క్రికెట్', 'krikket', 'Cricket', '🏏'],
    ['కబడ్డీ', 'kabaddi', 'Kabaddi', '🤼'],
    ['దాగుడుమూతలు', 'daagudumootalu', 'Hide and seek', '🙈'],
    ['లూడో', 'loodo', 'Ludo', '🎲'],
    ['చదరంగం', 'chadarangam', 'Chess', '♟️'],
    ['పరుగు', 'parugu', 'Running', '🏃'],
    ['జారుడుబండ', 'jaarudubanda', 'Slide', '🛷'],
    ['ఆట', 'aata', 'Game', '🎮'],
  ] },
];
