import type { UnitSpec } from './types';
export const PACK_C: UnitSpec[] = [
  { id: 'c-numbers-11', name: 'Counting 11 to 19', icon: '🔢', rows: [
    ['పదకొండు', 'padakondu', 'Eleven', '1️⃣'],
    ['పన్నెండు', 'pannendu', 'Twelve', '🕛'],
    ['పదమూడు', 'padamoodu', 'Thirteen', '🔢'],
    ['పద్నాలుగు', 'padnaalugu', 'Fourteen', '🔟'],
    ['పదిహేను', 'padihenu', 'Fifteen', '🖐️'],
    ['పదహారు', 'padahaaru', 'Sixteen', '🎂'],
    ['పదిహేడు', 'padihedu', 'Seventeen', '🎈'],
    ['పద్దెనిమిది', 'paddenimidi', 'Eighteen', '🎉'],
    ['పంతొమ్మిది', 'pantommidi', 'Nineteen', '🧮'],
    ['సున్నా', 'sunnaa', 'Zero', '⭕'],
  ] },
  { id: 'c-numbers-tens', name: 'Tens, Hundred, Thousand', icon: '💯', rows: [
    ['ఇరవై', 'iravai', 'Twenty', '2️⃣'],
    ['ముప్పై', 'muppai', 'Thirty', '3️⃣'],
    ['నలభై', 'nalabhai', 'Forty', '4️⃣'],
    ['యాభై', 'yaabhai', 'Fifty', '5️⃣'],
    ['అరవై', 'aravai', 'Sixty', '6️⃣'],
    ['డెబ్బై', 'debbai', 'Seventy', '7️⃣'],
    ['ఎనభై', 'enabhai', 'Eighty', '8️⃣'],
    ['తొంభై', 'tombhai', 'Ninety', '9️⃣'],
    ['వంద', 'vanda', 'Hundred', '💯'],
    ['వెయ్యి', 'veyyi', 'Thousand', '💰'],
    ['లక్ష', 'laksha', 'Lakh', '💵'],
  ] },
  { id: 'c-ordinals', name: 'First, Second, Half', icon: '🥇', rows: [
    ['మొదటి', 'modati', 'First', '🥇'],
    ['రెండవ', 'rendava', 'Second', '🥈'],
    ['మూడవ', 'moodava', 'Third', '🥉'],
    ['నాలుగవ', 'naalugava', 'Fourth', '4️⃣'],
    ['ఐదవ', 'aidava', 'Fifth', '5️⃣'],
    ['ఆఖరి', 'aakhari', 'Last', '🏁'],
    ['సగం', 'sagam', 'Half', '🌗'],
    ['పావు', 'paavu', 'Quarter', '🍰'],
    ['రెట్టింపు', 'rettimpu', 'Double', '✌️'],
    ['జత', 'jata', 'Pair', '🧦'],
  ] },
  { id: 'c-days', name: 'Days of the Week', icon: '📅', rows: [
    ['ఆదివారం', 'aadivaaram', 'Sunday', '☀️'],
    ['సోమవారం', 'somavaaram', 'Monday', '🌙'],
    ['మంగళవారం', 'mangalavaaram', 'Tuesday', '🔥'],
    ['బుధవారం', 'budhavaaram', 'Wednesday', '🌿'],
    ['గురువారం', 'guruvaaram', 'Thursday', '⭐'],
    ['శుక్రవారం', 'shukravaaram', 'Friday', '🌸'],
    ['శనివారం', 'shanivaaram', 'Saturday', '🪐'],
    ['రోజు', 'roju', 'Day', '📅'],
    ['సెలవు', 'selavu', 'Holiday', '🏖️'],
  ] },
  { id: 'c-months-1', name: 'Telugu Months 1', icon: '🌸', rows: [
    ['చైత్రం', 'chaitram', 'Chaitra', '🌸'],
    ['వైశాఖం', 'vaishaakham', 'Vaishakha', '🌞'],
    ['జ్యేష్ఠం', 'jyeshtham', 'Jyeshtha', '🔥'],
    ['ఆషాఢం', 'aashaadham', 'Ashadha', '☔'],
    ['శ్రావణం', 'shraavanam', 'Shravana', '🪔'],
    ['భాద్రపదం', 'bhaadrapadam', 'Bhadrapada', '🐘'],
    ['వసంతం', 'vasantam', 'Spring', '🌷'],
    ['వేసవి', 'vesavi', 'Summer', '🏖️'],
  ] },
  { id: 'c-months-2', name: 'Telugu Months 2', icon: '🪔', rows: [
    ['ఆశ్వయుజం', 'aashvayujam', 'Ashvayuja', '🏹'],
    ['కార్తీకం', 'kaarteekam', 'Kartika', '🪔'],
    ['మార్గశిరం', 'maargashiram', 'Margashira', '❄️'],
    ['పుష్యం', 'pushyam', 'Pushya', '🌾'],
    ['మాఘం', 'maagham', 'Magha', '🌄'],
    ['ఫాల్గుణం', 'phaalgunam', 'Phalguna', '🎨'],
    ['వానాకాలం', 'vaanaakaalam', 'Rainy season', '🌧️'],
    ['చలికాలం', 'chalikaalam', 'Winter', '🧣'],
  ] },
  { id: 'c-time', name: 'Time Words', icon: '⏰', rows: [
    ['వారం', 'vaaram', 'Week', '🗓️'],
    ['నెల', 'nela', 'Month', '📆'],
    ['సంవత్సరం', 'samvatsaram', 'Year', '🎊'],
    ['గంట', 'ganta', 'Hour', '🕐'],
    ['నిమిషం', 'nimisham', 'Minute', '⏱️'],
    ['సమయం', 'samayam', 'Time', '⏰'],
    ['ఇంతకు ముందు', 'intaku mundu', 'Before', '⏪'],
    ['ఆలస్యం', 'aalasyam', 'Late', '🕙'],
    ['ఎప్పుడూ', 'eppudoo', 'Always', '♾️'],
    ['అప్పుడప్పుడు', 'appudappudu', 'Sometimes', '🔀'],
    ['తర్వాత', 'tarvaata', 'After', '⏩'],
    ['త్వరలో', 'tvaralo', 'Soon', '🔜'],
    ['రోజూ', 'rojoo', 'Daily', '🔁'],
  ] },
  { id: 'c-size', name: 'Big and Small', icon: '🐘', rows: [
    ['పెద్ద', 'pedda', 'Big', '🐘'],
    ['చిన్న', 'chinna', 'Small', '🐜'],
    ['ఎత్తు', 'ettu', 'Tall', '🦒'],
    ['పొట్టి', 'potti', 'Short', '🩳'],
    ['పొడవు', 'poduvu', 'Long', '📏'],
    ['లావు', 'laavu', 'Fat', '🐷'],
    ['సన్నం', 'sannam', 'Thin', '🧵'],
    ['వెడల్పు', 'vedalpu', 'Wide', '🛣️'],
    ['ఇరుకు', 'iruku', 'Narrow', '🤏'],
    ['మందం', 'mandam', 'Thick', '📚'],
    ['లోతు', 'lotu', 'Deep', '🕳️'],
  ] },
  { id: 'c-opposites-1', name: 'Opposites 1', icon: '↔️', rows: [
    ['వేడి', 'vedi', 'Hot', '🔥'],
    ['చల్లని', 'challani', 'Cold', '🥶'],
    ['కొత్త', 'kotta', 'New', '🆕'],
    ['పాత', 'paata', 'Old', '👴'],
    ['శుభ్రం', 'shubhram', 'Clean', '🧼'],
    ['మురికి', 'muriki', 'Dirty', '🐖'],
    ['గట్టి', 'gatti', 'Hard', '💪'],
    ['మెత్తని', 'mettani', 'Soft', '🧸'],
    ['బరువు', 'baruvu', 'Heavy', '🏋️'],
    ['తేలిక', 'telika', 'Light', '🎈'],
    ['వేగంగా', 'vegangaa', 'Fast', '🐆'],
    ['నెమ్మదిగా', 'nemmadigaa', 'Slow', '🐌'],
  ] },
  { id: 'c-opposites-2', name: 'Opposites 2', icon: '🔄', rows: [
    ['దగ్గర', 'daggara', 'Near', '📍'],
    ['దూరం', 'dooram', 'Far', '🔭'],
    ['పైన', 'paina', 'Up', '⬆️'],
    ['కింద', 'kinda', 'Down', '⬇️'],
    ['నిండు', 'nindu', 'Full', '🥛'],
    ['ఖాళీ', 'khaali', 'Empty', '⭕'],
    ['తడి', 'tadi', 'Wet', '💦'],
    ['పొడి', 'podi', 'Dry', '🏜️'],
    ['లోపల', 'lopala', 'Inside', '📥'],
    ['బయట', 'bayata', 'Outside', '📤'],
    ['ఎడమ', 'edama', 'Left', '⬅️'],
    ['కుడి', 'kudi', 'Right', '➡️'],
  ] },
  { id: 'c-tastes', name: 'Tastes', icon: '😋', rows: [
    ['తీపి', 'teepi', 'Sweet', '🍬'],
    ['పులుపు', 'pulupu', 'Sour', '🍋'],
    ['ఉప్పగా', 'uppagaa', 'Salty', '🧂'],
    ['కారం', 'kaaram', 'Spicy', '🌶️'],
    ['చేదు', 'chedu', 'Bitter', '🤢'],
    ['రుచిగా', 'ruchigaa', 'Tasty', '😝'],
    ['కమ్మని', 'kammani', 'Yummy', '😋'],
    ['చప్పగా', 'chappagaa', 'Bland', '🥣'],
    ['పచ్చి', 'pachchi', 'Raw', '🥦'],
    ['పండిన', 'pandina', 'Ripe', '🍑'],
  ] },
  { id: 'c-qualities', name: 'Good and Bad', icon: '👍', rows: [
    ['మంచి', 'manchi', 'Good', '👍'],
    ['చెడ్డ', 'chedda', 'Bad', '👎'],
    ['అందమైన', 'andamaina', 'Beautiful', '🌹'],
    ['అల్లరి', 'allari', 'Naughty', '😜'],
    ['తెలివైన', 'telivaina', 'Clever', '🧠'],
    ['ధైర్యం', 'dhairyam', 'Courage', '🦁'],
    ['దయ', 'daya', 'Kindness', '🤗'],
    ['బద్ధకం', 'baddhakam', 'Laziness', '🦥'],
    ['నిజాయితీ', 'nijaayitee', 'Honesty', '😇'],
    ['మర్యాద', 'maryaada', 'Good manners', '🙏'],
    ['తప్పు', 'tappu', 'Wrong', '❌'],
    ['సరైన', 'saraina', 'Correct', '✅'],
  ] },
  { id: 'c-colours-2', name: 'More Colours', icon: '🎨', rows: [
    ['ఊదా రంగు', 'oodaa rangu', 'Purple', '🟣'],
    ['గోధుమ రంగు', 'godhuma rangu', 'Brown', '🟤'],
    ['బూడిద రంగు', 'boodida rangu', 'Grey', '☁️'],
    ['బంగారు రంగు', 'bangaaru rangu', 'Golden', '🌟'],
    ['వెండి రంగు', 'vendi rangu', 'Silver', '🥈'],
    ['లేత రంగు', 'leta rangu', 'Light colour', '🤍'],
    ['ముదురు రంగు', 'muduru rangu', 'Dark colour', '🖤'],
    ['ఆకుపచ్చ రంగు', 'aakupachcha rangu', 'Leaf green', '🌿'],
    ['రంగు', 'rangu', 'Colour', '🎨'],
    ['ఇంద్రధనుస్సు', 'indradhanussu', 'Rainbow', '🌈'],
  ] },
  { id: 'c-feelings-2', name: 'More Feelings', icon: '🥺', rows: [
    ['సిగ్గు', 'siggu', 'Shy', '🙈'],
    ['గర్వం', 'garvam', 'Proud', '😌'],
    ['ఉత్సాహం', 'utsaaham', 'Excited', '🤩'],
    ['అలసట', 'alasata', 'Tired', '😩'],
    ['విసుగు', 'visugu', 'Bored', '😑'],
    ['చింత', 'chinta', 'Worried', '😟'],
    ['ఆశ్చర్యం', 'aashcharyam', 'Surprised', '😲'],
    ['ఒంటరితనం', 'ontaritanam', 'Lonely', '🥺'],
    ['సారీ', 'saaree', 'Sorry', '🙏'],
    ['ఆనందం', 'aanandam', 'Joy', '😄'],
    ['అసూయ', 'asooya', 'Jealous', '😒'],
    ['నిరాశ', 'niraasha', 'Disappointed', '😞'],
  ] },
  { id: 'c-pronouns', name: 'I, You, He, She', icon: '🧑', rows: [
    ['నేను', 'nenu', 'I', '🙋'],
    ['నువ్వు', 'nuvvu', 'You', '👉'],
    ['మీరు', 'meeru', 'You (respect)', '🧓'],
    ['అతను', 'atanu', 'He', '👦'],
    ['ఆమె', 'aame', 'She', '👧'],
    ['మేము', 'memu', 'We', '🤗'],
    ['వాళ్ళు', 'vaallu', 'They', '🚶'],
    ['ఇది', 'idi', 'This', '👇'],
    ['అది', 'adi', 'That', '👆'],
    ['ఇవి', 'ivi', 'These', '🍎'],
  ] },
  { id: 'c-quantity', name: 'Here, There, Many', icon: '📍', rows: [
    ['ఇక్కడ', 'ikkada', 'Here', '📍'],
    ['అక్కడ', 'akkada', 'There', '👉'],
    ['అందరూ', 'andaroo', 'Everyone', '🌍'],
    ['కొన్ని', 'konni', 'Some', '🍪'],
    ['ఎన్నో', 'enno', 'Many', '🧮'],
    ['కొద్ది', 'koddi', 'Few', '🤏'],
    ['ఎక్కువ', 'ekkuva', 'More', '➕'],
    ['తక్కువ', 'takkuva', 'Less', '➖'],
    ['మధ్యలో', 'madhyalo', 'In the middle', '🎯'],
    ['ఇంకొకటి', 'inkokati', 'Another one', '☝️'],
  ] },
  { id: 'c-connectors', name: 'Little Words', icon: '🔗', rows: [
    ['కానీ', 'kaani', 'But', '↩️'],
    ['ఎందుకంటే', 'endukante', 'Because', '💭'],
    ['నాతో', 'naato', 'With me', '🤝'],
    ['లేకుండా', 'lekundaa', 'Without', '🚫'],
    ['ఇలా', 'ilaa', 'Like this', '👈'],
    ['చాలా', 'chaalaa', 'Very', '💯'],
    ['కొంచెం', 'konchem', 'Little', '🤏'],
    ['మళ్ళీ', 'mallee', 'Again', '🔁'],
    ['కూడా', 'koodaa', 'Also', '🔗'],
    ['మాత్రమే', 'maatrame', 'Only', '☝️'],
    ['లేదా', 'ledaa', 'Or', '🔀'],
  ] },
  { id: 'c-do-morning', name: 'Morning Routine', icon: '🌅', rows: [
    ['లే', 'le', 'Wake up', '⏰'],
    ['పళ్ళు తోముకో', 'pallu tomuko', 'Brush teeth', '🦷'],
    ['స్నానం చెయ్యి', 'snaanam cheyyi', 'Bathe', '🚿'],
    ['తుడుచుకో', 'tuduchuko', 'Dry off', '🧻'],
    ['వేసుకో', 'vesuko', 'Wear', '👕'],
    ['దువ్వుకో', 'duvvuko', 'Comb', '💇'],
    ['తయారవ్వు', 'tayaaravvu', 'Get ready', '🎒'],
    ['బయలుదేరు', 'bayaluderu', 'Leave', '🚶'],
  ] },
  { id: 'c-do-moving', name: 'Moving Words', icon: '🏃', rows: [
    ['పరిగెత్తు', 'parigettu', 'Run', '🏃'],
    ['నడు', 'nadu', 'Walk', '🚶'],
    ['దూకు', 'dooku', 'Jump', '🦘'],
    ['ఈత కొట్టు', 'eeta kottu', 'Swim', '🏊'],
    ['ఎక్కు', 'ekku', 'Climb', '🧗'],
    ['పడు', 'padu', 'Fall', '🍂'],
    ['నిలబడు', 'nilabadu', 'Stand', '🧍'],
    ['తిరుగు', 'tirugu', 'Turn', '🔄'],
    ['ఎగురు', 'eguru', 'Fly', '🕊️'],
    ['సైకిల్ తొక్కు', 'saikil tokku', 'Ride cycle', '🚴'],
    ['ఆగు', 'aagu', 'Stop', '🛑'],
    ['జారు', 'jaaru', 'Slide', '🎢'],
  ] },
  { id: 'c-do-hands', name: 'Using Hands', icon: '🤲', rows: [
    ['ఇవ్వు', 'ivvu', 'Give', '🎁'],
    ['తీసుకో', 'teesuko', 'Take', '🤲'],
    ['తీసుకురా', 'teesukuraa', 'Bring', '🛍️'],
    ['పెట్టు', 'pettu', 'Put', '📌'],
    ['తెరువు', 'teruvu', 'Open', '🔓'],
    ['మూయి', 'mooyi', 'Close', '🔒'],
    ['విసురు', 'visuru', 'Throw', '⚾'],
    ['పట్టుకో', 'pattuko', 'Catch', '🧤'],
    ['నెట్టు', 'nettu', 'Push', '⏩'],
    ['లాగు', 'laagu', 'Pull', '⏪'],
    ['కోయి', 'koyi', 'Cut', '🔪'],
    ['పగలగొట్టు', 'pagalagottu', 'Break', '💥'],
  ] },
  { id: 'c-do-talking', name: 'Talking and Thinking', icon: '💬', rows: [
    ['మాట్లాడు', 'maatlaadu', 'Speak', '🗣️'],
    ['అడుగు', 'adugu', 'Ask', '❓'],
    ['చెప్పు', 'cheppu', 'Tell', '📢'],
    ['విను', 'vinu', 'Listen', '👂'],
    ['ఆలోచించు', 'aalochinchu', 'Think', '🤔'],
    ['తెలుసు', 'telusu', 'Know', '💡'],
    ['కావాలి', 'kaavaali', 'Want', '🙋'],
    ['ఇష్టపడు', 'ishtapadu', 'Like', '❤️'],
    ['గుర్తుపెట్టుకో', 'gurtupettuko', 'Remember', '🧠'],
    ['మర్చిపో', 'marchipo', 'Forget', '🤷'],
    ['నవ్వు', 'navvu', 'Laugh', '😂'],
    ['ఏడువు', 'aeduvu', 'Cry', '😢'],
  ] },
  { id: 'c-do-calling', name: 'Calling and Caring', icon: '📣', rows: [
    ['పిలువు', 'piluvu', 'Call', '📞'],
    ['కేక వెయ్యి', 'keka veyyi', 'Shout', '📣'],
    ['జవాబు చెప్పు', 'javaabu cheppu', 'Answer', '💬'],
    ['నమ్ము', 'nammu', 'Believe', '🤞'],
    ['ఒప్పుకో', 'oppuko', 'Agree', '🤝'],
    ['మెచ్చుకో', 'mechchuko', 'Praise', '👏'],
    ['తిట్టు', 'tittu', 'Scold', '😠'],
    ['కల కను', 'kala kanu', 'Dream', '💭'],
    ['ప్రేమించు', 'preminchu', 'Love', '😍'],
    ['భయపడు', 'bhayapadu', 'Be scared', '😨'],
  ] },
  { id: 'c-do-learning', name: 'Learning and Making', icon: '✍️', rows: [
    ['గీయి', 'geeyi', 'Draw', '🖍️'],
    ['లెక్కపెట్టు', 'lekkapettu', 'Count', '🧮'],
    ['నేర్చుకో', 'nerchuko', 'Learn', '🎓'],
    ['నేర్పు', 'nerpu', 'Teach', '🏫'],
    ['ఇల్లు కట్టు', 'illu kattu', 'Build', '🏗️'],
    ['వండు', 'vandu', 'Cook', '🍳'],
    ['శుభ్రం చెయ్యి', 'shubhram cheyyi', 'Clean', '🧽'],
    ['ఊడ్చు', 'oodchu', 'Sweep', '🧹'],
    ['సరిచెయ్యి', 'saricheyyi', 'Fix', '🔧'],
    ['తుడువు', 'tuduvu', 'Wipe', '🧻'],
    ['మడత పెట్టు', 'madata pettu', 'Fold', '🧺'],
  ] },
  { id: 'c-do-crafts', name: 'Kitchen and Crafts', icon: '✂️', rows: [
    ['కుట్టు', 'kuttu', 'Sew', '🧵'],
    ['రంగు వెయ్యి', 'rangu veyyi', 'Colour in', '🎨'],
    ['అతికించు', 'atikinchu', 'Stick', '📎'],
    ['కత్తిరించు', 'kattirinchu', 'Snip', '✂️'],
    ['కట్టు', 'kattu', 'Tie', '🎀'],
    ['విప్పు', 'vippu', 'Untie', '🎀'],
    ['పోయి', 'poyi', 'Pour', '🚰'],
    ['కలుపు', 'kalupu', 'Mix', '🥣'],
    ['ఉడికించు', 'udikinchu', 'Boil', '🍲'],
    ['వేయించు', 'veyinchu', 'Fry', '🍟'],
  ] },
  { id: 'c-do-body', name: 'Body Actions', icon: '🤧', rows: [
    ['తాకు', 'taaku', 'Touch', '👆'],
    ['నమలు', 'namalu', 'Chew', '🥜'],
    ['మింగు', 'mingu', 'Swallow', '💊'],
    ['ఊదు', 'oodu', 'Blow', '🎈'],
    ['కొరుకు', 'koruku', 'Bite', '🦷'],
    ['తుమ్ము', 'tummu', 'Sneeze', '🤧'],
    ['దగ్గు', 'daggu', 'Cough', '😷'],
    ['చప్పట్లు కొట్టు', 'chappatlu kottu', 'Clap', '👏'],
    ['ఆవలించు', 'aavalinchu', 'Yawn', '🥱'],
    ['కళ్ళు మూసుకో', 'kallu moosuko', 'Close eyes', '🙈'],
  ] },
  { id: 'c-do-market', name: 'At the Market', icon: '🛒', rows: [
    ['కొను', 'konu', 'Buy', '🛒'],
    ['అమ్ము', 'ammu', 'Sell', '🏷️'],
    ['డబ్బులు ఇవ్వు', 'dabbulu ivvu', 'Pay', '💳'],
    ['వెతుకు', 'vetuku', 'Search', '🔍'],
    ['కనుక్కో', 'kanukko', 'Find out', '✅'],
    ['దాచు', 'daachu', 'Hide', '🕵️'],
    ['చూపించు', 'choopinchu', 'Show', '👉'],
    ['పంచు', 'panchu', 'Share', '🍰'],
    ['గెలువు', 'geluvu', 'Win', '🏆'],
    ['ఓడిపో', 'odipo', 'Lose', '😞'],
    ['ఎదురుచూడు', 'eduruchoodu', 'Wait', '⏳'],
    ['సహాయం చెయ్యి', 'sahaayam cheyyi', 'Help', '🆘'],
  ] },
];
