import type { UnitSpec } from './types';
export const PACK_A: UnitSpec[] = [
  { id: 'a-relatives', name: 'More relatives', icon: '👪', rows: [
    ['బావ', 'baava', "Sister's husband", '🧑'],
    ['అత్త', 'atta', "Aunt (father's sister)", '🧕'],
    ['పిన్ని', 'pinni', "Mom's younger sister", '👩'],
    ['పెద్దమ్మ', 'peddamma', "Mom's elder sister", '👵'],
    ['బాబాయి', 'baabaayi', "Dad's younger brother", '👨'],
    ['పెద్దనాన్న', 'peddanaanna', "Dad's elder brother", '👴'],
    ['వదిన', 'vadina', "Elder brother's wife", '👩'],
    ['కొడుకు', 'koduku', 'Son', '👦'],
    ['కూతురు', 'kooturu', 'Daughter', '👧'],
    ['కోడలు', 'kodalu', 'Daughter-in-law', '👰'],
    ['అల్లుడు', 'alludu', 'Son-in-law', '🤵'],
    ['మనవడు', 'manavadu', 'Grandson', '🧒'],
  ] },
  { id: 'a-people', name: 'People around me', icon: '🧑‍🤝‍🧑', rows: [
    ['పసిపాప', 'pasipaapa', 'Baby', '👶'],
    ['పాప', 'paapa', 'Little girl', '👧'],
    ['బాబు', 'baabu', 'Little boy', '👦'],
    ['అతిథి', 'athithi', 'Guest', '🙏'],
    ['పక్కింటివాళ్ళు', 'pakkintivaallu', 'Neighbours', '🏘️'],
    ['స్నేహితుడు', 'snehitudu', 'Friend', '🤝'],
    ['టీచర్', 'teechar', 'Teacher', '🏫'],
    ['డాక్టర్', 'daaktar', 'Doctor', '🩺'],
    ['వంటవాడు', 'vantavaadu', 'Cook', '🍳'],
    ['రైతు', 'raitu', 'Farmer', '🌾'],
    ['పోలీసు', 'poleesu', 'Police', '👮'],
    ['డ్రైవర్', 'draivar', 'Driver', '🚕'],
  ] },
  { id: 'a-kitchen', name: 'Kitchen things', icon: '🍳', rows: [
    ['చెంచా', 'chenchaa', 'Spoon', '🥄'],
    ['పళ్ళెం', 'pallem', 'Plate', '🍽️'],
    ['గ్లాసు', 'glaasu', 'Glass', '🥛'],
    ['కుండ', 'kunda', 'Clay pot', '🏺'],
    ['పొయ్యి', 'poyyi', 'Stove', '🔥'],
    ['కత్తి', 'katti', 'Knife', '🔪'],
    ['పెనం', 'penam', 'Tawa, flat pan', '🥞'],
    ['గరిటె', 'garite', 'Ladle', '🥣'],
    ['కుక్కర్', 'kukkar', 'Cooker', '🥘'],
    ['మూత', 'moota', 'Lid', '🍲'],
    ['రోలు', 'rolu', 'Grinding stone', '⚫'],
    ['బాణలి', 'baanali', 'Frying pan', '🍳'],
  ] },
  { id: 'a-spices', name: 'Spices and flavours', icon: '🌶️', rows: [
    ['జీలకర్ర', 'jeelakarra', 'Cumin', '🌾'],
    ['ఆవాలు', 'aavaalu', 'Mustard seeds', '🟤'],
    ['మిరియాలు', 'miriyaalu', 'Pepper', '⚫'],
    ['యాలకులు', 'yaalakulu', 'Cardamom', '🌱'],
    ['ధనియాలు', 'dhaniyaalu', 'Coriander seeds', '🟢'],
    ['లవంగాలు', 'lavangaalu', 'Cloves', '🌰'],
    ['చింతపండు', 'chintapandu', 'Tamarind', '🟫'],
    ['బెల్లం', 'bellam', 'Jaggery', '🍫'],
    ['కరివేపాకు', 'karivepaaku', 'Curry leaves', '🍃'],
    ['అల్లం', 'allam', 'Ginger', '🍂'],
    ['వెల్లుల్లి', 'vellulli', 'Garlic', '🧄'],
  ] },
  { id: 'a-grains', name: 'Grains and pulses', icon: '🌾', rows: [
    ['బియ్యం', 'biyyam', 'Rice, uncooked', '🌾'],
    ['గోధుమలు', 'godhumalu', 'Wheat', '🍞'],
    ['జొన్నలు', 'jonnalu', 'Sorghum', '🌿'],
    ['రాగులు', 'raagulu', 'Ragi, finger millet', '🌱'],
    ['మొక్కజొన్న', 'mokkajonna', 'Corn', '🌽'],
    ['పెసలు', 'pesalu', 'Green gram', '🟢'],
    ['శనగలు', 'shanagalu', 'Chickpeas', '🟡'],
    ['మినుములు', 'minumulu', 'Black gram', '⚫'],
    ['కందిపప్పు', 'kandipappu', 'Toor dal', '🥣'],
    ['వేరుశనగలు', 'verushanagalu', 'Peanuts', '🥜'],
    ['నువ్వులు', 'nuvvulu', 'Sesame seeds', '⚪'],
    ['అటుకులు', 'atukulu', 'Flattened rice', '🍘'],
  ] },
  { id: 'a-veg2', name: 'More vegetables', icon: '🥦', rows: [
    ['క్యాబేజీ', 'kyaabejee', 'Cabbage', '🥬'],
    ['కాలీఫ్లవర్', 'kaaleeflavar', 'Cauliflower', '🥦'],
    ['బీరకాయ', 'beerakaaya', 'Ridge gourd', '🥒'],
    ['సొరకాయ', 'sorakaaya', 'Bottle gourd', '🍈'],
    ['కాకరకాయ', 'kaakarakaaya', 'Bitter gourd', '🟢'],
    ['దొండకాయ', 'dondakaaya', 'Ivy gourd', '🌿'],
    ['పొట్లకాయ', 'potlakaaya', 'Snake gourd', '🐍'],
    ['గుమ్మడికాయ', 'gummadikaaya', 'Pumpkin', '🎃'],
    ['ముల్లంగి', 'mullangi', 'Radish', '⚪'],
    ['బీన్స్', 'beens', 'Beans', '🌱'],
    ['బఠానీలు', 'bataaneelu', 'Peas', '🟩'],
    ['అరటికాయ', 'aratikaaya', 'Raw banana', '🍌'],
  ] },
  { id: 'a-veg3', name: 'Leaves and roots', icon: '🥬', rows: [
    ['కొత్తిమీర', 'kottimeera', 'Coriander leaves', '🌿'],
    ['పుదీనా', 'pudeenaa', 'Mint', '🍃'],
    ['పాలకూర', 'paalakoora', 'Spinach', '🥬'],
    ['తోటకూర', 'totakoora', 'Amaranth leaves', '☘️'],
    ['గోంగూర', 'gongoora', 'Sorrel leaves', '🍀'],
    ['చిలగడదుంప', 'chilagadadumpa', 'Sweet potato', '🍠'],
    ['కంద', 'kanda', 'Yam', '🟤'],
    ['చామదుంప', 'chaamadumpa', 'Colocasia root', '🥔'],
    ['మునగకాయ', 'munagakaaya', 'Drumstick', '🥒'],
    ['పచ్చిమిర్చి', 'pachchimirchi', 'Green chilli', '🌶️'],
    ['మామిడికాయ', 'maamidikaaya', 'Raw mango', '🥭'],
    ['ఉల్లికాడలు', 'ullikaadalu', 'Spring onion', '🧅'],
  ] },
  { id: 'a-fruits2', name: 'More fruits', icon: '🍊', rows: [
    ['బొప్పాయి', 'boppaayi', 'Papaya', '🟧'],
    ['నారింజ', 'naarinja', 'Orange', '🍊'],
    ['దానిమ్మ', 'daanimma', 'Pomegranate', '🔴'],
    ['సపోటా', 'sapotaa', 'Sapota', '🟤'],
    ['పైనాపిల్', 'painaapil', 'Pineapple', '🍍'],
    ['స్ట్రాబెర్రీ', 'straberree', 'Strawberry', '🍓'],
    ['బత్తాయి', 'battaayi', 'Sweet lime', '🟡'],
    ['కర్బూజ', 'karbooja', 'Muskmelon', '🍈'],
    ['సీతాఫలం', 'seetaaphalam', 'Custard apple', '🍏'],
    ['పనసపండు', 'panasapandu', 'Jackfruit', '🌳'],
    ['కివి', 'kivi', 'Kiwi', '🥝'],
  ] },
  { id: 'a-fruits3', name: 'Fruits and nuts', icon: '🥜', rows: [
    ['నేరేడుపండు', 'neredupandu', 'Jamun fruit', '🟣'],
    ['ఉసిరికాయ', 'usirikaaya', 'Gooseberry', '🟢'],
    ['రేగుపండు', 'regupandu', 'Ber fruit', '🍎'],
    ['తాటి ముంజలు', 'taati munjalu', 'Ice apple', '🥥'],
    ['చెరుకు', 'cheruku', 'Sugarcane', '🎋'],
    ['ఖర్జూరం', 'kharjooram', 'Dates', '🌴'],
    ['అంజీర', 'anjeera', 'Fig', '🍈'],
    ['పియర్', 'piyar', 'Pear', '🍐'],
    ['జీడిపప్పు', 'jeedipappu', 'Cashew nuts', '🥜'],
    ['బాదం', 'baadam', 'Almonds', '🌰'],
    ['పిస్తా', 'pistaa', 'Pistachios', '🟩'],
    ['కిస్మిస్', 'kismis', 'Raisins', '🍇'],
  ] },
  { id: 'a-snacks', name: 'Telugu snacks', icon: '🥨', rows: [
    ['మురుకులు', 'murukulu', 'Murukulu, crunchy twirls', '🥨'],
    ['పునుగులు', 'punugulu', 'Punugulu, fried dough balls', '🧆'],
    ['మిర్చి బజ్జీ', 'mirchi bajjee', 'Chilli fritter', '🌶️'],
    ['గారెలు', 'gaarelu', 'Vada, savoury doughnut', '🍩'],
    ['పకోడీ', 'pakodee', 'Pakoda', '🍤'],
    ['ఉప్మా', 'upmaa', 'Upma', '🥣'],
    ['సమోసా', 'samosaa', 'Samosa', '🥟'],
    ['బోండా', 'bondaa', 'Bonda', '🍘'],
    ['పెసరట్టు', 'pesarattu', 'Green gram dosa', '🥞'],
    ['మిక్చర్', 'mikchar', 'Mixture snack', '🥜'],
    ['బొరుగులు', 'borugulu', 'Puffed rice', '🍿'],
    ['చిప్స్', 'chips', 'Chips', '🍟'],
  ] },
  { id: 'a-sweets', name: 'Sweets', icon: '🍬', rows: [
    ['లడ్డు', 'laddu', 'Laddu', '🟠'],
    ['జిలేబీ', 'jilebee', 'Jalebi', '🍥'],
    ['పాయసం', 'paayasam', 'Payasam, milk pudding', '🥣'],
    ['హల్వా', 'halvaa', 'Halwa', '🟧'],
    ['బొబ్బట్లు', 'bobbatlu', 'Bobbatlu, sweet flatbread', '🥞'],
    ['అరిసెలు', 'ariselu', 'Arisalu, sweet rice cakes', '🍪'],
    ['సున్నుండలు', 'sunnundalu', 'Black gram laddu', '🟤'],
    ['కజ్జికాయలు', 'kajjikaayalu', 'Sweet dumplings', '🥟'],
    ['బూరెలు', 'boorelu', 'Boorelu, sweet balls', '🍩'],
    ['గులాబ్ జామూన్', 'gulaab jaamoon', 'Gulab jamun', '🍮'],
    ['చాక్లెట్', 'chaaklet', 'Chocolate', '🍫'],
    ['ఐస్ క్రీమ్', 'ais kreem', 'Ice cream', '🍦'],
  ] },
  { id: 'a-drinks', name: 'Drinks and dairy', icon: '🥛', rows: [
    ['టీ', 'tee', 'Tea', '🍵'],
    ['కాఫీ', 'kaafee', 'Coffee', '☕'],
    ['మజ్జిగ', 'majjiga', 'Buttermilk', '🥛'],
    ['నెయ్యి', 'neyyi', 'Ghee', '🟡'],
    ['వెన్న', 'venna', 'Butter', '🧈'],
    ['జ్యూస్', 'jyoos', 'Juice', '🧃'],
    ['కొబ్బరి నీళ్ళు', 'kobbari neellu', 'Coconut water', '🥥'],
    ['చెరుకు రసం', 'cheruku rasam', 'Sugarcane juice', '🎋'],
    ['లస్సీ', 'lassee', 'Lassi', '🍹'],
    ['నిమ్మరసం', 'nimmarasam', 'Lemon juice', '🍋'],
    ['పనీర్', 'paneer', 'Paneer', '🧀'],
    ['సోడా', 'sodaa', 'Soda', '🥤'],
  ] },
  { id: 'a-dishes', name: 'Dishes at a meal', icon: '🍛', rows: [
    ['సాంబారు', 'saambaaru', 'Sambar', '🍲'],
    ['రసం', 'rasam', 'Rasam, pepper soup', '🥣'],
    ['కూర', 'koora', 'Curry', '🥘'],
    ['ఊరగాయ', 'ooragaaya', 'Pickle', '🥒'],
    ['అప్పడాలు', 'appadaalu', 'Papad', '🍘'],
    ['పచ్చడి', 'pachchadi', 'Chutney', '🥗'],
    ['బిర్యానీ', 'biryaanee', 'Biryani', '🍛'],
    ['పులిహోర', 'pulihora', 'Tamarind rice', '🍋'],
    ['పెరుగన్నం', 'perugannam', 'Curd rice', '🍚'],
    ['పొంగలి', 'pongali', 'Pongal', '🍥'],
    ['వేపుడు', 'vepudu', 'Fry', '🍳'],
    ['పూరీ', 'pooree', 'Poori', '🥯'],
  ] },
  { id: 'a-morning', name: 'Morning and bath', icon: '🛁', rows: [
    ['సబ్బు', 'sabbu', 'Soap', '🧼'],
    ['తువ్వాలు', 'tuvvaalu', 'Towel', '🧖'],
    ['బ్రష్', 'brash', 'Toothbrush', '🦷'],
    ['పేస్టు', 'pestu', 'Toothpaste', '🧴'],
    ['దువ్వెన', 'duvvena', 'Comb', '💇'],
    ['అద్దం', 'addam', 'Mirror', '🔍'],
    ['మగ్గు', 'maggu', 'Mug', '🥛'],
    ['షాంపూ', 'shaampoo', 'Shampoo', '🚿'],
    ['స్నానం', 'snaanam', 'Bath', '🛁'],
    ['వేడి నీళ్ళు', 'vedi neellu', 'Hot water', '♨️'],
    ['చల్ల నీళ్ళు', 'challa neellu', 'Cold water', '🧊'],
    ['పౌడర్', 'paudar', 'Powder', '✨'],
  ] },
  { id: 'a-sleep', name: 'Time to sleep', icon: '😴', rows: [
    ['దిండు', 'dindu', 'Pillow', '🛌'],
    ['దుప్పటి', 'duppati', 'Blanket', '🧣'],
    ['చాప', 'chaapa', 'Mat', '🟫'],
    ['పరుపు', 'parupu', 'Mattress', '🛏️'],
    ['దోమతెర', 'domatera', 'Mosquito net', '🦟'],
    ['జోల', 'jola', 'Lullaby', '🎶'],
    ['కల', 'kala', 'Dream', '💭'],
    ['గురక', 'guraka', 'Snoring', '💤'],
    ['కథ', 'katha', 'Story', '📖'],
    ['పైజామా', 'paijaamaa', 'Pyjamas', '👖'],
    ['ఆవలింత', 'aavalinta', 'Yawn', '🥱'],
    ['చీకటి', 'cheekati', 'Darkness', '🌑'],
  ] },
  { id: 'a-house1', name: 'Things at home 1', icon: '🔑', rows: [
    ['తాళం చెవి', 'taalam chevi', 'Key', '🔑'],
    ['తాళం', 'taalam', 'Lock', '🔒'],
    ['ఫ్యాన్', 'phyaan', 'Fan', '🌀'],
    ['లైటు', 'laitu', 'Light', '💡'],
    ['టీవీ', 'teevee', 'TV', '📺'],
    ['ఫోను', 'phonu', 'Phone', '📱'],
    ['సంచి', 'sanchi', 'Bag', '👜'],
    ['గొడుగు', 'godugu', 'Umbrella', '☂️'],
    ['చీపురు', 'cheepuru', 'Broom', '🧹'],
    ['బకెట్', 'baket', 'Bucket', '🛁'],
    ['అగ్గిపెట్టె', 'aggipette', 'Matchbox', '🔥'],
    ['కరెంటు', 'karentu', 'Electricity', '⚡'],
  ] },
  { id: 'a-house2', name: 'Things at home 2', icon: '🧰', rows: [
    ['రిమోట్', 'remot', 'Remote', '🎛️'],
    ['బ్యాటరీ', 'byaatari', 'Battery', '🔋'],
    ['టార్చి', 'taarchi', 'Torch', '🔦'],
    ['కొవ్వొత్తి', 'kovvotti', 'Candle', '🕯️'],
    ['అలమారా', 'alamaaraa', 'Cupboard', '🗄️'],
    ['సూది', 'soodi', 'Needle', '🧵'],
    ['దారం', 'daaram', 'Thread', '🧵'],
    ['సుత్తి', 'sutti', 'Hammer', '🔨'],
    ['తాడు', 'taadu', 'Rope', '➰'],
    ['చెత్త డబ్బా', 'chetta dabbaa', 'Dustbin', '🗑️'],
    ['ఇస్త్రీపెట్టె', 'istreepette', 'Iron box', '👔'],
  ] },
  { id: 'a-rooms', name: 'Rooms of a home', icon: '🏡', rows: [
    ['వంటగది', 'vantagadi', 'Kitchen', '🍳'],
    ['పడకగది', 'padakagadi', 'Bedroom', '🛏️'],
    ['స్నానాల గది', 'snaanaala gadi', 'Bathroom', '🛁'],
    ['హాలు', 'haalu', 'Hall', '🛋️'],
    ['పూజ గది', 'pooja gadi', 'Prayer room', '🛕'],
    ['డాబా', 'daabaa', 'Roof terrace', '🏠'],
    ['వరండా', 'varandaa', 'Veranda', '🏡'],
    ['తోట', 'tota', 'Garden', '🌳'],
    ['గేటు', 'getu', 'Gate', '🚧'],
    ['మెట్లు', 'metlu', 'Stairs', '⬆️'],
    ['గోడ', 'goda', 'Wall', '🧱'],
  ] },
  { id: 'a-furniture', name: 'Furniture and boxes', icon: '📦', rows: [
    ['బల్ల', 'balla', 'Table', '🍽️'],
    ['బీరువా', 'beeruvaa', 'Wardrobe', '🚪'],
    ['సోఫా', 'sofaa', 'Sofa', '🛋️'],
    ['స్టూలు', 'stoolu', 'Stool', '🪑'],
    ['డబ్బా', 'dabbaa', 'Tin box', '📦'],
    ['సీసా', 'seesaa', 'Bottle', '🍾'],
    ['బుట్ట', 'butta', 'Basket', '🧺'],
    ['పెట్టె', 'pette', 'Trunk box', '🧳'],
    ['కూజా', 'koojaa', 'Water jug', '🏺'],
    ['బిందె', 'binde', 'Water pot', '🚰'],
    ['చెంబు', 'chembu', 'Small pot', '🏺'],
    ['జాడీ', 'jaadee', 'Jar', '🍯'],
  ] },
  { id: 'a-ingredients', name: 'Cooking ingredients', icon: '🧂', rows: [
    ['నూనె', 'noone', 'Oil', '🛢️'],
    ['పిండి', 'pindi', 'Flour', '🌾'],
    ['పంచదార', 'panchadaara', 'Sugar', '🍚'],
    ['మసాలా', 'masaalaa', 'Masala', '🌶️'],
    ['రవ్వ', 'ravva', 'Semolina', '🥣'],
    ['సేమియా', 'semiyaa', 'Vermicelli', '🍜'],
    ['పోపు', 'popu', 'Tempering', '🍳'],
    ['కొబ్బరి', 'kobbari', 'Coconut', '🥥'],
    ['శనగపిండి', 'shanagapindi', 'Gram flour', '🟡'],
    ['బియ్యప్పిండి', 'biyyappindi', 'Rice flour', '⚪'],
    ['ఇంగువ', 'inguva', 'Hing, asafoetida', '🧂'],
  ] },
  { id: 'a-tastes', name: 'Tastes and cooking', icon: '😋', rows: [
    ['వంట', 'vanta', 'Cooking', '🍲'],
    ['మంట', 'manta', 'Flame', '🔥'],
    ['పొగ', 'poga', 'Smoke', '💨'],
    ['ఆవిరి', 'aaviri', 'Steam', '♨️'],
    ['రుచి', 'ruchi', 'Taste', '👅'],
    ['వాసన', 'vaasana', 'Smell', '👃'],
  ] },
  { id: 'a-eggmeat', name: 'Eggs, meat and fish', icon: '🥚', rows: [
    ['గుడ్డు', 'guddu', 'Egg', '🥚'],
    ['ఆమ్లెట్', 'aamlet', 'Omelette', '🍳'],
    ['మాంసం', 'maamsam', 'Meat', '🥩'],
    ['చికెన్', 'chiken', 'Chicken', '🍗'],
    ['మటన్', 'matan', 'Mutton', '🍖'],
    ['రొయ్యలు', 'royyalu', 'Prawns', '🦐'],
    ['ఎండు చేప', 'endu chepa', 'Dried fish', '🐟'],
    ['చేపల పులుసు', 'chepala pulusu', 'Fish curry', '🍲'],
    ['కబాబ్', 'kabaab', 'Kebab', '🍢'],
    ['చేపల వేపుడు', 'chepala vepudu', 'Fish fry', '🥘'],
  ] },
  { id: 'a-school', name: 'My school bag', icon: '🎒', rows: [
    ['స్కూలు సంచి', 'skoolu sanchi', 'School bag', '🎒'],
    ['నోటు పుస్తకం', 'notu pustakam', 'Notebook', '📓'],
    ['లంచ్ బాక్స్', 'lanch baaks', 'Lunch box', '🍱'],
    ['నీళ్ళ సీసా', 'neella seesa', 'Water bottle', '💧'],
    ['రంగు పెన్సిళ్ళు', 'rangu pensillu', 'Colour pencils', '🖍️'],
    ['షార్పనర్', 'sharpanar', 'Sharpener', '✂️'],
  ] },
];
